import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import ContractShell from '../ContractShell';
import { AuthContext } from '../../auth/state';
import { Context } from '../state';
import { ApiClient } from '../../api/client';
const capabilities = ['memberships.read', 'users.create', 'users.invite', 'users.status', 'users.password_reset', 'roles.read', 'roles.assign', 'roles.manage', 'audit.read', 'logs.access.read'];
const context = { id: 'scope-a', tenant_name: 'Empresa A', contract_id: 'contract-a', contract_code: 'CTR-A', environment: 'TEST', expires_at: '2099-01-01T00:00:00Z', capabilities };
const member = { id: 'member-a', user_id: 'user-a', display_name: 'Ana Silva', email: 'ana@example.test', role_id: 'buyer', role_name: 'Comprador Nacional', active: true, blocked: false, invitation_pending: true, invitation_status: 'QUEUED', last_access_at: null, version: 3, allowed_actions: ['invite', 'reset_password', 'block', 'inactivate', 'assign_role'] };
const buyer = { id: 'buyer', code: 'BUYER', name: 'Comprador Nacional', description: 'Compras', sensitivity_locked: false, support_eligible: true, classification: 'STANDARD', permissions: [], active: true, support_assignable: true, version: 2, member_count: 4 };
const calls: {
    path: string;
    init: RequestInit;
}[] = [];
let currentMember = member;
let membersStatus = 200, mutationStatus = 200, roleOptions = [buyer], total = 1;
function response(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status }); }
function mount(actor: 'PLATFORM_ADMIN' | 'PLATFORM_SUPPORT' = 'PLATFORM_ADMIN', grants = capabilities) {
    const api = new ApiClient();
    api.setContext(context.id);
    const tree = (scope: typeof context) => <AuthContext.Provider value={{ api, user: { user_id: 'operator', display_name: 'Operator', platform_role: actor }, loading: false, busy: false, error: null, login: async () => { }, logout: async () => { }, retry: () => { } }}><Context.Provider value={{ selected: { ...scope, capabilities: grants }, loading: false, busy: false, error: null, recovering: false, select: async () => { }, clear: async () => { }, retry: () => { } }}><ContractShell /></Context.Provider></AuthContext.Provider>;
    const view = render(tree(context));
    return { ...view, changeContext: (scope: typeof context) => { api.setContext(scope.id); view.rerender(tree(scope)); } };
}
beforeEach(() => { calls.length = 0; currentMember = member; membersStatus = 200; mutationStatus = 200; roleOptions = [buyer]; total = 1; vi.stubGlobal('fetch', vi.fn(async (url: string, init: RequestInit = {}) => { const path = url.replace('/api', ''); calls.push({ path, init }); if (path === '/auth/csrf')
    return response({ token: 'csrf' }); if (init.method && init.method !== 'GET')
    return response(init.method === 'POST' ? { status: 'accepted' } : member, mutationStatus); if (path.startsWith('/memberships?'))
    return response({ items: total ? [member] : [], total, limit: 20, offset: Number(new URL(url, 'http://localhost').searchParams.get('offset')) }, membersStatus); if (path === '/memberships/member-a')
    return response(currentMember); if (path.includes('/access-history'))
    return response({ items: [], next_cursor: null }); if (path.startsWith('/roles'))
    return response({ items: roleOptions, total: roleOptions.length, limit: 20, offset: 0 }); if (path === '/capabilities')
    return response({ items: [{ code: 'purchase.read', domain: 'purchase', sensitive: false }, { code: 'finance.read', domain: 'finance', sensitive: true }] }); if (path.startsWith('/audit?'))
    return response({ items: [{ id: 'event-a', occurred_at: '2026-10-01T12:00:00Z', action: 'membership.block', outcome: 'SUCCESS', actor_name: 'Operator', entity_type: 'membership', entity_id: 'member-a', request_id: 'request-a', reference: null }], next_cursor: 'next-page' }); if (path === '/audit/event-a')
    return response({ before: { active: true }, after: { active: false }, reason: 'Alteração autorizada' }); return response({}, 404); })); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('admin menus follow contextual capabilities and keeps context visible', async () => { mount(); expect(await screen.findByRole('button', { name: 'Usuários' })).toBeVisible(); expect(screen.getByRole('button', { name: 'Perfis' })).toBeVisible(); expect(screen.getByRole('button', { name: 'Auditoria' })).toBeVisible(); for (const text of ['Empresa A', 'CTR-A', 'Teste'])
    expect(screen.getByTestId('contract-context')).toHaveTextContent(text); await screen.findByText('Ana Silva'); expect(new Headers(calls.find(c => c.path.startsWith('/memberships?'))?.init.headers).get('X-HiAtlas-Context')).toBe('scope-a'); });
it('support uses only server role options and has no roles management menu', async () => { mount('PLATFORM_SUPPORT'); await screen.findByText('Ana Silva'); expect(screen.queryByRole('button', { name: 'Perfis' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Histórico' })).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: 'Novo usuário' })); expect(await screen.findByRole('option', { name: 'Comprador Nacional' })).toBeVisible(); expect(screen.queryByRole('option', { name: 'Financeiro' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Criar perfil' })).not.toBeInTheDocument(); });
it('does not infer capabilities from platform admin identity', async () => { mount('PLATFORM_ADMIN', []); expect(screen.queryByRole('button', { name: 'Usuários' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Perfis' })).not.toBeInTheDocument(); expect(await screen.findByText('Nenhuma ferramenta disponível neste contexto.')).toBeVisible(); expect(calls).toHaveLength(0); });
it('server filters and bounded pagination never fetch unbounded users', async () => { total = 45; mount(); await screen.findByText('Ana Silva'); fireEvent.change(screen.getByLabelText('Nome ou e-mail'), { target: { value: 'Ana' } }); fireEvent.change(screen.getByLabelText('Estado do vínculo'), { target: { value: 'BLOCKED' } }); fireEvent.click(screen.getByRole('button', { name: 'Pesquisar usuários' })); await waitFor(() => expect(calls.some(c => c.path.includes('search=Ana') && c.path.includes('status=BLOCKED') && c.path.includes('limit=20'))).toBe(true)); fireEvent.click(screen.getByRole('button', { name: 'Próxima página' })); await waitFor(() => expect(calls.some(c => c.path.includes('offset=20'))).toBe(true)); });
it('failed list offers retry and clears error into actual empty state', async () => { membersStatus = 503; mount(); expect(await screen.findByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível'); membersStatus = 200; total = 0; fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByText('Nenhum usuário encontrado neste contrato.')).toBeVisible(); expect(screen.queryByRole('alert')).not.toBeInTheDocument(); });
it('detail distinguishes identity, active and blocked, and actual invitation state', async () => { mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); expect(await screen.findByText('Identidade')).toBeVisible(); expect(screen.getByText('Vínculo neste contrato')).toBeVisible(); expect(screen.getByText('Último acesso não registrado neste contexto.')).toBeVisible(); expect(screen.getByText('Convite: Na fila')).toBeVisible(); expect(screen.getAllByText('Ativo').length).toBeGreaterThan(0); expect(screen.queryByText(/e-mail enviado/i)).not.toBeInTheDocument(); });
it('invitation requires contextual confirmation and neutral accepted result', async () => { mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Reemitir convite' })); const dialog = screen.getByRole('dialog'); expect(dialog).toHaveTextContent('Empresa A'); expect(dialog).toHaveTextContent('CTR-A'); expect(dialog).toHaveTextContent('convite anterior será invalidado'); expect(calls.some(c => c.path.endsWith('/invite'))).toBe(false); fireEvent.click(within(dialog).getByRole('button', { name: 'Confirmar' })); expect(await screen.findByText(/Solicitação aceita/)).toBeVisible(); expect(calls.find(c => c.path.endsWith('/invite'))?.init.method).toBe('POST'); });
it('409 keeps confirmation open, refreshes version and never claims success', async () => { mutationStatus = 409; mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Bloquear acesso' })); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Os dados foram alterados. Atualize a página e tente novamente.'); expect(screen.getByRole('dialog')).toBeVisible(); expect(screen.queryByText('Alteração concluída.')).not.toBeInTheDocument(); });
it('403 assignment keeps dialog and reloads eligible role options', async () => { mount('PLATFORM_SUPPORT'); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Alterar perfil' })); await within(screen.getByRole('dialog')).findByRole('option', { name: 'Comprador Nacional' }); mutationStatus = 403; roleOptions = []; fireEvent.change(screen.getByLabelText('Novo perfil'), { target: { value: 'buyer' } }); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Acesso negado'); await waitFor(() => expect(within(screen.getByRole('dialog')).queryByRole('option', { name: 'Comprador Nacional' })).not.toBeInTheDocument()); expect(screen.getByRole('dialog')).toBeVisible(); });
it('new user review shows context and submits minimal identity and eligible role', async () => { mount(); await screen.findByText('Ana Silva'); fireEvent.click(screen.getByRole('button', { name: 'Novo usuário' })); await screen.findByRole('option', { name: 'Comprador Nacional' }); fireEvent.change(screen.getByLabelText('Nome'), { target: { value: 'Beatriz' } }); fireEvent.change(screen.getByLabelText('E-mail'), { target: { value: 'bia@example.test' } }); fireEvent.change(screen.getByLabelText('Perfil'), { target: { value: 'buyer' } }); fireEvent.click(screen.getByRole('button', { name: 'Revisar solicitação' })); expect(screen.getByRole('dialog')).toHaveTextContent('bia@example.test'); expect(screen.getByRole('dialog')).toHaveTextContent('CTR-A'); fireEvent.click(screen.getByRole('button', { name: 'Confirmar' })); expect(await screen.findByText(/Solicitação aceita/)).toBeVisible(); expect(JSON.parse(String(calls.find(c => c.path === '/memberships')?.init.body))).toEqual({ display_name: 'Beatriz', email: 'bia@example.test', role_id: 'buyer' }); });
it('role management presents catalogue, impact, default false and reviews sensitive grants', async () => { mount(); fireEvent.click(screen.getByRole('button', { name: 'Perfis' })); expect(await screen.findByText('4 vínculos')).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: 'Criar perfil' })); expect(await screen.findByLabelText(/finance.read \(sensível\)/)).toBeVisible(); expect(screen.getByLabelText('Atribuível pelo suporte')).not.toBeChecked(); fireEvent.change(screen.getByLabelText('Código'), { target: { value: 'FIN' } }); fireEvent.change(screen.getByLabelText('Nome do perfil'), { target: { value: 'Financeiro' } }); fireEvent.click(screen.getByLabelText(/finance.read \(sensível\)/)); fireEvent.click(screen.getByRole('button', { name: 'Revisar perfil' })); expect(screen.getByRole('dialog')).toHaveTextContent('Permissões sensíveis'); expect(screen.getByRole('dialog')).toHaveTextContent('Empresa A'); });
it('support history shows only sanitized projection and filters cursor requests', async () => { mount('PLATFORM_SUPPORT'); fireEvent.click(screen.getByRole('button', { name: 'Histórico' })); expect(await screen.findByText(/membership.block/)).toBeVisible(); expect(screen.queryByText('Alteração autorizada')).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Detalhes do evento' })).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Ação'), { target: { value: 'membership.block' } }); fireEvent.click(screen.getByRole('button', { name: 'Filtrar histórico' })); await waitFor(() => expect(calls.some(c => c.path.includes('action=membership.block'))).toBe(true)); fireEvent.click(screen.getByRole('button', { name: 'Próximos eventos' })); await waitFor(() => expect(calls.some(c => c.path.includes('cursor=next-page'))).toBe(true)); });
it('conflict refresh cannot resubmit until refreshed member has arrived', async () => { mutationStatus = 409; const original = fetch; let hold = false, resolveDetail: ((response: Response) => void) | undefined; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/memberships/member-a' && hold ? new Promise<Response>(resolve => { resolveDetail = resolve; }) : original(url, init))); mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Bloquear acesso' })); hold = true; fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByRole('alert'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Atualizar dados' })); expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })).toBeDisabled(); resolveDetail?.(response({ ...member, version: 4 })); });
it.each([
    ['inactivate', 'Inativar vínculo', { active: false }],
    ['activate', 'Ativar vínculo', { active: true }],
    ['block', 'Bloquear acesso', { blocked: true }],
    ['unblock', 'Desbloquear acesso', { blocked: false }],
])('confirms %s independently with contextual optimistic version', async (action, label, change) => { currentMember = { ...member, active: action === 'activate' ? false : true, blocked: action === 'unblock', allowed_actions: [action] }; mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: label })); expect(screen.getByRole('dialog')).toHaveTextContent('Estado atual:'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByText('Alteração concluída.'); expect(JSON.parse(String(calls.find(c => c.path.endsWith('/status'))?.init.body))).toEqual({ expected_version: 3, ...change }); });
it('reset issues only a link request without password fields or delivery claims', async () => { currentMember = { ...member, invitation_pending: false, allowed_actions: ['reset_password'] }; mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Enviar link de redefinição' })); expect(screen.getByRole('dialog')).toHaveTextContent('Apenas o destinatário define a senha'); expect(screen.queryByLabelText('Senha')).not.toBeInTheDocument(); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByText(/Solicitação aceita/); expect(calls.find(c => c.path.endsWith('/reset-password'))?.init.method).toBe('POST'); });
it('server actions constrain buttons even with all contextual grants', async () => { currentMember = { ...member, allowed_actions: [] }; mount(); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); await screen.findByText('Vínculo neste contrato'); for (const name of ['Alterar perfil', 'Bloquear acesso', 'Reemitir convite', 'Enviar link de redefinição'])
    expect(screen.queryByRole('button', { name })).not.toBeInTheDocument(); });
it('role assignment confirms server role name and commits contextual expected version', async () => { roleOptions = [buyer, { ...buyer, id: 'coordinator', name: 'Coordenação' }]; mount('PLATFORM_SUPPORT'); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); fireEvent.click(await screen.findByRole('button', { name: 'Alterar perfil' })); await within(screen.getByRole('dialog')).findByRole('option', { name: 'Coordenação' }); fireEvent.change(screen.getByLabelText('Novo perfil'), { target: { value: 'coordinator' } }); expect(screen.getByRole('dialog')).toHaveTextContent('Novo perfil: Coordenação'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByText('Alteração concluída.'); expect(JSON.parse(String(calls.find(c => c.path.endsWith('/role'))?.init.body))).toEqual({ role_id: 'coordinator', expected_version: 3 }); });
it('creates profile only after review with default support flag false', async () => { mount(); fireEvent.click(screen.getByRole('button', { name: 'Perfis' })); await screen.findByText('4 vínculos'); fireEvent.click(screen.getByRole('button', { name: 'Criar perfil' })); await screen.findByLabelText(/purchase.read/); fireEvent.change(screen.getByLabelText('Código'), { target: { value: 'BUY' } }); fireEvent.change(screen.getByLabelText('Nome do perfil'), { target: { value: 'Compras locais' } }); fireEvent.change(screen.getByLabelText('Descrição'), { target: { value: 'Compras autorizadas' } }); fireEvent.click(screen.getByLabelText(/purchase.read/)); fireEvent.click(screen.getByRole('button', { name: 'Revisar perfil' })); expect(calls.some(c => c.path === '/roles' && c.init.method === 'POST')).toBe(false); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByText('Perfil salvo.'); expect(JSON.parse(String(calls.find(c => c.path === '/roles' && c.init.method === 'POST')?.init.body))).toEqual({ code: 'BUY', name: 'Compras locais', description: 'Compras autorizadas', classification: 'STANDARD', active: true, support_assignable: false, permissions: ['purchase.read'] }); });
it('profile edit reviews member impact and sends expected version without editing code', async () => { mount(); fireEvent.click(screen.getByRole('button', { name: 'Perfis' })); fireEvent.click(await screen.findByRole('button', { name: 'Editar perfil Comprador Nacional' })); await screen.findByLabelText(/purchase.read/); expect(screen.getByLabelText('Código')).toBeDisabled(); fireEvent.click(screen.getByLabelText('Atribuível pelo suporte')); fireEvent.click(screen.getByLabelText('Perfil ativo')); fireEvent.click(screen.getByRole('button', { name: 'Revisar perfil' })); expect(screen.getByRole('dialog')).toHaveTextContent('4 vínculos'); expect(screen.getByRole('dialog')).toHaveTextContent('perfil será inativado'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); await screen.findByText('Perfil salvo.'); const body = JSON.parse(String(calls.find(c => c.path === '/roles/buyer')?.init.body)); expect(body.expected_version).toBe(2); expect(body.active).toBe(false); expect(body.support_assignable).toBe(false); expect(body.code).toBeUndefined(); });
it('profile conflict keeps review and forbids reuse of stale role version', async () => { mutationStatus = 409; mount(); fireEvent.click(screen.getByRole('button', { name: 'Perfis' })); fireEvent.click(await screen.findByRole('button', { name: 'Editar perfil Comprador Nacional' })); await screen.findByLabelText(/purchase.read/); fireEvent.click(screen.getByRole('button', { name: 'Revisar perfil' })); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Os dados foram alterados'); expect(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar' })).toBeDisabled(); expect(screen.queryByText('Perfil salvo.')).not.toBeInTheDocument(); });
it('admin audit fetches only requested authorized event details and member history stays contextual', async () => { mount(); fireEvent.click(screen.getByRole('button', { name: 'Auditoria' })); await screen.findByText(/membership.block/); expect(calls.some(c => c.path === '/audit/event-a')).toBe(false); fireEvent.click(screen.getByRole('button', { name: 'Detalhes do evento' })); await screen.findByText(/Alteração autorizada/); expect(new Headers(calls.find(c => c.path === '/audit/event-a')?.init.headers).get('X-HiAtlas-Context')).toBe('scope-a'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Cancelar' })); fireEvent.click(screen.getByRole('button', { name: 'Usuários' })); fireEvent.click(await screen.findByRole('button', { name: 'Detalhes de Ana Silva' })); await screen.findByRole('heading', { name: 'Histórico do vínculo' }); await waitFor(() => expect(calls.some(c => c.path.startsWith('/memberships/member-a/access-history?limit=20'))).toBe(true)); });
it('cancel restores keyboard focus and prevents a reviewed issuance', async () => { mount(); await screen.findByText('Ana Silva'); const trigger = screen.getByRole('button', { name: 'Novo usuário' }); trigger.focus(); fireEvent.click(trigger); await within(screen.getByRole('dialog')).findByRole('option', { name: 'Comprador Nacional' }); fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' }); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(trigger).toHaveFocus(); expect(calls.some(c => c.path === '/memberships' && c.init.method === 'POST')).toBe(false); });
it('context change aborts delayed membership reads and discards old-context identity', async () => { const original = fetch; let resolveA: ((response: Response) => void) | undefined, signal: AbortSignal | undefined; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url.startsWith('/api/memberships?') && new Headers(init?.headers).get('X-HiAtlas-Context') === 'scope-a' ? new Promise<Response>(resolve => { resolveA = resolve; signal = init?.signal ?? undefined; }) : original(url, init))); const view = mount(); await screen.findByText('Carregando usuários…'); await waitFor(() => expect(resolveA).toBeDefined()); view.changeContext({ ...context, id: 'scope-b', tenant_name: 'Empresa B', contract_code: 'CTR-B' }); await screen.findByText('Ana Silva'); expect(signal?.aborted).toBe(true); resolveA!(response({ items: [{ ...member, display_name: 'Detalhe exclusivo A' }], total: 1, limit: 20, offset: 0 })); await waitFor(() => expect(screen.queryByText('Detalhe exclusivo A')).not.toBeInTheDocument()); expect(screen.getByTestId('contract-context')).toHaveTextContent('Empresa B'); });
it('role selectors page server options instead of treating first page as all roles', async () => { const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url.startsWith('/api/roles/assignable?') ? Promise.resolve(response({ items: url.includes('offset=20') ? [{ ...buyer, id: 'next-role', name: 'Próximo perfil' }] : [buyer], total: 21, limit: 20, offset: url.includes('offset=20') ? 20 : 0 })) : original(url, init))); mount('PLATFORM_SUPPORT'); await screen.findByText('Ana Silva'); fireEvent.click(screen.getByRole('button', { name: 'Novo usuário' })); await within(screen.getByRole('dialog')).findByRole('option', { name: 'Comprador Nacional' }); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Próximos perfis' })); expect(await within(screen.getByRole('dialog')).findByRole('option', { name: 'Próximo perfil' })).toBeVisible(); expect(within(screen.getByRole('dialog')).queryByRole('option', { name: 'Comprador Nacional' })).not.toBeInTheDocument(); });
it('failed conflict reload keeps submission gated until a successful current version arrives',async()=>{mutationStatus=409;const original=fetch;let failDetail=false,failedReads=0;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/memberships/member-a'&&failDetail?(failedReads++,Promise.resolve(response({},503))):original(url,init)));mount();fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana Silva'}));fireEvent.click(await screen.findByRole('button',{name:'Bloquear acesso'}));failDetail=true;fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar'}));await within(screen.getByRole('dialog')).findByText(/Os dados foram alterados/);fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Atualizar dados'}));await waitFor(()=>expect(failedReads).toBeGreaterThanOrEqual(2));expect(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar'})).toBeDisabled();failDetail=false;currentMember={...member,version:4};mutationStatus=200;fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Atualizar dados'}));await waitFor(()=>expect(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar'})).toBeEnabled());fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar'}));await screen.findByText('Alteração concluída.');expect(JSON.parse(String(calls.filter(c=>c.path.endsWith('/status')).at(-1)?.init.body)).expected_version).toBe(4);});
it('admin can explicitly clear historical support flag on locked role but cannot reenable it',async()=>{roleOptions=[{...buyer,sensitivity_locked:true,support_assignable:true}];mount();fireEvent.click(screen.getByRole('button',{name:'Perfis'}));fireEvent.click(await screen.findByRole('button',{name:'Editar perfil Comprador Nacional'}));await screen.findByLabelText(/purchase.read/);const flag=screen.getByLabelText('Atribuível pelo suporte');expect(flag).toBeChecked();expect(flag).toBeEnabled();fireEvent.click(flag);expect(flag).not.toBeChecked();expect(flag).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Revisar perfil'}));expect(screen.getByRole('dialog')).toHaveTextContent('elegibilidade de novas atribuições');fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar'}));await screen.findByText('Perfil salvo.');expect(JSON.parse(String(calls.find(c=>c.path==='/roles/buyer')?.init.body)).support_assignable).toBe(false);});



it('profile review translates classification into the same Portuguese label as the form',async()=>{mount();fireEvent.click(screen.getByRole('button',{name:'Perfis'}));await screen.findByText('4 vínculos');fireEvent.click(screen.getByRole('button',{name:'Criar perfil'}));await screen.findByLabelText(/purchase.read/);fireEvent.change(screen.getByLabelText('Código'),{target:{value:'FIN'}});fireEvent.change(screen.getByLabelText('Nome do perfil'),{target:{value:'Financeiro'}});fireEvent.change(screen.getByLabelText('Classificação'),{target:{value:'FINANCIAL_FISCAL'}});fireEvent.click(screen.getByRole('button',{name:'Revisar perfil'}));expect(screen.getByRole('dialog')).toHaveTextContent('Classificação: Financeiro / fiscal');});
it('role picker exposes stable exact accessible field names independent of loaded option text',async()=>{mount();await screen.findByText('Ana Silva');fireEvent.click(screen.getByRole('button',{name:'Novo usuário'}));await within(screen.getByRole('dialog')).findByRole('option',{name:'Comprador Nacional'});expect(within(screen.getByRole('dialog')).getByRole('combobox',{name:'Perfil'})).toHaveAttribute('aria-label','Perfil');});
