import { useState } from 'react';
import ErrorNotice from '../../api/ErrorNotice';
import { useScopedQuery } from '../access/useScopedQuery';
import type { OrganizationNode, Page, Parent } from './types';
export default function ParentOptions({ kind, excluded, value, onChange, canHaveParent, disabled = false }: { kind: string; excluded?: string; value: Parent | null; onChange: (parent: Parent | null) => void; canHaveParent: boolean; disabled?: boolean }) {
 const [search, setSearch] = useState(''), [filter, setFilter] = useState(''), [offset, setOffset] = useState(0);
 const query = new URLSearchParams({limit:'20',offset:String(offset),parent_for_kind:kind});
 if(excluded) query.set('exclude_descendants_of',excluded);
 if(filter) query.set('search',filter);
 const {data,error,loading,retry} = useScopedQuery<Page<OrganizationNode>>(canHaveParent && kind ? `/organization/nodes?${query}` : null);
 const selectedOutsidePage = value && !data?.items.some(item => item.id === value.id);
 return <fieldset className="parent-picker"><legend>Pai físico permitido</legend><label>Buscar unidade pai<input aria-label="Buscar unidade pai" value={search} maxLength={200} disabled={disabled || !canHaveParent} onChange={event=>setSearch(event.target.value)}/></label><button type="button" disabled={disabled || !canHaveParent || loading} onClick={()=>{setOffset(0);setFilter(search.trim());retry();}}>Pesquisar pais</button><label>Unidade pai<select aria-label="Unidade pai" value={value?.id ?? ''} disabled={disabled || !canHaveParent || loading || !!error} onChange={event=>onChange(data?.items.find(item=>item.id===event.target.value) ?? null)}><option value="">Sem pai (raiz)</option>{selectedOutsidePage && <option value={value.id}>{value.name} ({value.code})</option>}{data?.items.map(item=><option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select></label>{!canHaveParent && <p>Este tipo é uma raiz física.</p>}{loading && <p role="status">Carregando pais permitidos…</p>}<ErrorNotice error={error}/>{!!error && <button type="button" disabled={disabled} onClick={retry}>Tentar novamente (pais)</button>}{data?.total===0 && <p>Nenhum pai ativo permitido para este tipo. A unidade pode ser uma raiz.</p>}{data && data.total>data.limit && <div className="pagination"><button type="button" disabled={disabled || loading || offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Pais anteriores</button><span>{offset+1}–{Math.min(offset+data.items.length,data.total)} de {data.total} pais</span><button type="button" disabled={disabled || loading || offset+data.limit>=data.total} onClick={()=>setOffset(offset+20)}>Próximos pais</button></div>}<p>Somente pais ativos autorizados neste contrato. O servidor valida a hierarquia ao salvar.</p></fieldset>;
}
