import type { HorizonSignal, PurchaseScope } from './types'
const signals: HorizonSignal[] = [
 { id: 'int-free-time', purchaseScope: 'INTERNATIONAL', window: 'TODAY', kind: 'ACTION', severity: 'Crítico', title: 'Free Time crítico', summary: 'Container disponível em Santos: rolamentos e válvulas industriais.', impact: 'Devolução após amanhã pode gerar US$ 150 por dia de demurrage.', recommendation: 'Confirmar retirada hoje e reservar descarga e devolução do vazio.', evidence: ['Free Time termina amanhã às 18h; tarifa demonstrativa de US$ 150/dia.', 'Descarga exige 8 horas e o transportador ainda não confirmou a coleta.'], entityLabel: 'Container', entityId: 'MSCU1234567', company: 'Aurora Distribuição', unit: 'Matriz' },
 { id: 'nac-bauru', purchaseScope: 'NATIONAL', window: 'TODAY', kind: 'ACTION', severity: 'Crítico', title: 'CD Bauru · família Aço', summary: 'Carga rodoviária em trânsito com perfis, juntas e cantoneiras.', impact: 'Cobertura de 3 dias contra ETA em 5 dias: risco de ruptura por 2 dias.', recommendation: 'Confirmar antecipação com a transportadora e avaliar transferência para Bauru.', evidence: ['Estoque disponível: 300 peças; consumo médio: 100 peças/dia.', 'Carga já expedida; ETA em 5 dias para o CD Bauru.'], entityLabel: 'Carga', entityId: 'NAC-2026-01842', company: 'Aurora Distribuição', unit: 'Matriz' },
 { id: 'int-stock', purchaseScope: 'INTERNATIONAL', window: 'DAYS_1_7', kind: 'RISK', severity: 'Atenção', title: 'Rolamentos: estoque antes do ETA', summary: 'Lote importado de rolamentos em trânsito marítimo para Santos.', impact: 'Cobertura de 4 dias e ETA em 6 dias deixam 2 dias sem atendimento.', recommendation: 'Validar transferência de 200 peças e confirmar ETA com o agente.', evidence: ['Saldo disponível de 400 peças; consumo projetado de 100 peças/dia.', 'Booking confirmado com chegada em 6 dias; sem lote alternativo liberado.'], entityLabel: 'Lote importado', entityId: 'IMP-2026-042', company: 'Aurora Distribuição', unit: 'Matriz' },
 { id: 'int-overstock', purchaseScope: 'INTERNATIONAL', window: 'DAYS_7_30', kind: 'OPPORTUNITY', severity: 'Em dia', title: 'Reprogramar compra de válvulas', summary: 'Pedido futuro pode elevar o estoque acima da cobertura alvo.', impact: 'Cobertura projetada de 60 dias para meta de 30 dias; capital imobilizado desnecessário.', recommendation: 'Negociar entrega parcelada antes de confirmar a próxima compra.', evidence: ['Saldo e recebimentos previstos somam 1.800 peças; consumo de 30 peças/dia.', 'Meta de cobertura de 900 peças; pedido de 900 peças ainda pode ser reprogramado.'], entityLabel: 'Pedido', entityId: 'INT-2026-087', company: 'Aurora Distribuição', unit: 'Matriz' },
 { id: 'nac-stock', purchaseScope: 'NATIONAL', window: 'DAYS_1_7', kind: 'RISK', severity: 'Atenção', title: 'Aço: ruptura antes da chegada', summary: 'Destino Bauru: chegada rodoviária prevista em 5 dias.', impact: 'Há uma lacuna de 200 peças entre o fim da cobertura e o recebimento.', recommendation: 'Reservar transferência de 200 peças de outra unidade enquanto a carga chega.', evidence: ['Cobertura termina em 3 dias; consumo de 100 peças/dia.', 'ETA confirmado para daqui a 5 dias; intervalo descoberto de 2 dias.'], entityLabel: 'Planejamento da carga', entityId: 'PLN-BAURU-01842', company: 'Aurora Distribuição', unit: 'Matriz' },
 { id: 'nac-reorder', purchaseScope: 'NATIONAL', window: 'DAYS_7_30', kind: 'OPPORTUNITY', severity: 'Em dia', title: 'Revisar ponto de pedido do Aço', summary: 'Ajustar parâmetros de reposição para o próximo ciclo nacional.', impact: 'O ponto atual de 400 peças não cobre lead time de 5 dias e segurança de 2 dias.', recommendation: 'Avaliar ponto de pedido de 700 peças, com 200 peças de estoque de segurança.', evidence: ['Consumo demonstrativo de 100 peças/dia × lead time de 5 dias = 500 peças.', 'Estoque de segurança de 200 peças: ponto de pedido recomendado de 700 peças.'], entityLabel: 'Família de materiais', entityId: 'ACO-BAURU', company: 'Aurora Distribuição', unit: 'Matriz' },
]
export function getDemoSignals(scope: PurchaseScope): HorizonSignal[] {
 return signals.filter(signal => signal.purchaseScope === scope)
}


export const buyerConfiguration: Record<PurchaseScope, {label: string; indicators: {label: string; value: string}[]}> = {
 INTERNATIONAL: {label: 'Comprador Internacional', indicators: [
  {label: 'USD/BRL', value: 'R$ 5,45'}, {label: 'EUR/BRL', value: 'R$ 5,91'}, {label: 'Containers em trânsito', value: '1'},
 ]},
 NATIONAL: {label: 'Comprador Nacional', indicators: [
  {label: 'Cargas em trânsito', value: '1'}, {label: 'Entregas previstas hoje', value: '0'}, {label: 'Entregas atrasadas', value: '0'},
 ]},
}
