import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {AuthContext,type Auth} from '../auth/state';
import {Context,type ContextState} from '../platform/state';
import {ApiClient} from '../api/client';
import ExcelPage from './ExcelPage';

const catalog={profile:'Perfil sintético',units:[],items:[{id:'COMPRADOR_NACIONAL',version:1,label:'Comprador Nacional',available:true,can_download:true,can_import:true,can_export:true,datasets:['PRODUCTS']},{id:'FINANCEIRO',version:1,label:'Financeiro',available:false,can_download:false,can_import:false,can_export:false,datasets:[]}]};
const base={id:'import-syn',status:'READY_FOR_CONFIRMATION',version:3,template_id:'COMPRADOR_NACIONAL',template_version:1,row_count:1,error_count:0,warning_count:0,inserted_count:0,skipped_count:0,preview_expires_at:'2099-01-01T00:00:00Z',result_code:'PREVIEW_READY'};
let preview={...base},failure=0;
const calls: {path:string;init:RequestInit}[]=[];
function response(value:unknown,status=200){return new Response(JSON.stringify(value),{status});}
beforeEach(()=>{preview={...base};failure=0;calls.length=0;vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit={})=>{const path=url.replace('/api','');calls.push({path,init});if(path==='/auth/csrf')return response({token:'synthetic'});if(path==='/datahub/templates')return response(catalog);if(path.startsWith('/datahub/imports?'))return response({items:[],total:0,page:1,page_size:10});if(path==='/datahub/imports')return response(preview,201);if(path.endsWith('/rows?page=1&page_size=20'))return response({items:[{id:'row',dataset:'PRODUCTS',sheet:'Produtos',source_row:13,validation_status:'VALID',payload:{codigo:'000123',descricao:'Produto sintético'}}],total:1,page:1,page_size:20});if(path.endsWith('/issues?page=1&page_size=20'))return response({items:preview.error_count?[{sheet:'Produtos',source_row:13,column:'codigo',severity:'ERROR',code:'INVALID_FIELD',message:'Campo inválido.'}]:[],total:preview.error_count,page:1,page_size:20});if(path.endsWith('/confirm'))return failure?response({code:'CONFLICT'},failure):response({...preview,status:'COMMITTED',version:4,inserted_count:1});if(path.endsWith('/download')||path==='/datahub/exports')return new Response('synthetic xlsx');return response({},404);}));vi.stubGlobal('URL',class extends URL{static createObjectURL=vi.fn(()=> 'blob:synthetic');static revokeObjectURL=vi.fn();});});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
function mount(){const api=new ApiClient();api.setContext('opaque');const auth={api,user:{user_id:'user',display_name:'Usuário sintético',platform_role:null},loading:false,busy:false,error:null,login:vi.fn(),logout:vi.fn(),retry:vi.fn()} as Auth;const state={selected:{id:'opaque',tenant_name:'Empresa sintética',contract_id:'c',contract_code:'SYN-A',environment:'TEST',expires_at:'2099-01-01T00:00:00Z',capabilities:['datahub.read','datahub.import']},loading:false,busy:false,error:null,recovering:false,select:vi.fn(),clear:vi.fn(),retry:vi.fn()} as ContextState;return render(<AuthContext.Provider value={auth}><Context.Provider value={state}><ExcelPage/></Context.Provider></AuthContext.Provider>);}
async function upload(){await screen.findByLabelText('Planilha XLSX');fireEvent.change(screen.getByLabelText('Planilha XLSX'),{target:{files:[new File(['synthetic'],'synthetic.xlsx')]}});fireEvent.click(screen.getByRole('button',{name:'Validar e gerar preview'}));await screen.findByRole('heading',{name:'Revisar importação'});}
it('download official template and financial unavailable',async()=>{mount();await screen.findByLabelText('Modelo oficial');fireEvent.click(screen.getByRole('button',{name:'Baixar modelo oficial'}));await waitFor(()=>expect(calls.some(c=>c.path.endsWith('/download'))).toBe(true));expect(screen.getByText('Financeiro indisponível nesta V1.')).toBeInTheDocument();});
it('preview errors block confirmation',async()=>{preview={...base,status:'REJECTED',error_count:1};mount();await upload();expect(await screen.findByText(/Campo inválido/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Revisar e confirmar importação'})).not.toBeInTheDocument();});
it('warnings show skipped count and confirmation is contextual',async()=>{preview={...base,warning_count:1,skipped_count:1};mount();await upload();expect(screen.getByText(/1 ignorada/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar e confirmar importação'}));const dialog=screen.getByRole('dialog');expect(within(dialog).getByText(/Empresa sintética/)).toBeInTheDocument();expect(within(dialog).getByText(/SYN-A/)).toBeInTheDocument();fireEvent.keyDown(dialog,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();});
it('confirm only shows committed success with closed command',async()=>{mount();await upload();expect(screen.queryByText('Importação concluída.')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar e confirmar importação'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar importação'}));await screen.findByText('Importação concluída.');const command=JSON.parse(calls.find(c=>c.path.endsWith('/confirm'))!.init.body as string);expect(Object.keys(command).sort()).toEqual(['expected_version','idempotency_key']);});
it.each([403,409,503])('failure %s never shows success',async(status)=>{failure=status;mount();await upload();fireEvent.click(screen.getByRole('button',{name:'Revisar e confirmar importação'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar importação'}));await screen.findByRole('alert');expect(screen.queryByText('Importação concluída.')).not.toBeInTheDocument();if(status===409)expect(screen.getByText(/novo preview/i)).toBeInTheDocument();});
it('expired preview blocks confirmation',async()=>{preview={...base,status:'EXPIRED'};mount();await upload();expect(screen.getByText(/Preview expirado/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Revisar e confirmar importação'})).not.toBeInTheDocument();});

it('export requires confirmation and releases object URL',async()=>{mount();await screen.findByLabelText('Modelo oficial');fireEvent.click(screen.getByRole('button',{name:'Exportar dados'}));expect(calls.some(c=>c.path==='/datahub/exports')).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Confirmar exportação'}));await waitFor(()=>expect(URL.revokeObjectURL).toHaveBeenCalled());expect(document.querySelector('a[download]')).toBeNull();});
it('unmount discards delayed preview and aborts request',async()=>{const original=fetch;let done!:(v:Response)=>void;let requestSignal:AbortSignal|null=null;vi.stubGlobal('fetch',vi.fn((url:string,init:RequestInit={})=>{if(url==='/api/datahub/imports'){requestSignal=init.signal as AbortSignal;return new Promise<Response>(resolve=>{done=resolve;});}return original(url,init);}));const mounted=mount();await screen.findByLabelText('Planilha XLSX');fireEvent.change(screen.getByLabelText('Planilha XLSX'),{target:{files:[new File(['synthetic'],'synthetic.xlsx')]}});fireEvent.click(screen.getByRole('button',{name:'Validar e gerar preview'}));await waitFor(()=>expect(done).toBeDefined());mounted.unmount();expect(requestSignal!.aborted).toBe(true);done(response(base,201));await new Promise(resolve=>setTimeout(resolve,0));expect(screen.queryByRole('heading',{name:'Revisar importação'})).not.toBeInTheDocument();});
it('current server permissions control upload and export',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init:RequestInit={})=>url==='/api/datahub/templates'?Promise.resolve(response({...catalog,items:catalog.items.map(t=>({...t,can_import:false,can_export:false}))})):original(url,init)));mount();await screen.findByLabelText('Modelo oficial');expect(screen.queryByLabelText('Planilha XLSX')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Exportar dados'})).toBeDisabled();});
