import {useState} from 'react';
import ErrorNotice from '../api/ErrorNotice';
import {useDataHub} from './useDataHub';
import TemplatePicker from './TemplatePicker';
import UploadForm from './UploadForm';
import ImportPreview from './ImportPreview';
import ConfirmImportDialog from './ConfirmImportDialog';
import ExportDialog from './ExportDialog';
import ImportHistory from './ImportHistory';
import './DataHub.css';
export default function ExcelPage(){const state=useDataHub();const [templateId,setTemplate]=useState(''),[nodes,setNodes]=useState<string[]>([]),[confirm,setConfirm]=useState(false),[exporting,setExporting]=useState(false);const template=state.catalog?.items.find(t=>t.id===templateId&&t.available)??state.catalog?.items.find(t=>t.available&&t.label===state.catalog?.profile)??state.catalog?.items.find(t=>t.available)??null;const canConfirm=state.preview?.status==='READY_FOR_CONFIRMATION'&&state.preview.error_count===0&&state.catalog?.items.some(t=>t.id===state.preview?.template_id&&t.can_import);return <section className="access-page datahub-page"><h2>Data Hub &gt; Excel</h2><p>Modelos oficiais e registros informacionais de Supply Chain. Preview obrigatório antes da gravação.</p><p>Financeiro indisponível nesta V1.</p>{state.busy&&<p role="status">Processando solicitação…</p>}<ErrorNotice error={state.error}/>{!!state.error&&<button disabled={state.busy} onClick={()=>void state.reload()}>Tentar novamente</button>}{state.notice&&<p role="status">{state.notice}</p>}{state.catalog&&<><TemplatePicker catalog={state.catalog} selected={template} onChange={setTemplate} busy={state.busy} nodes={nodes} onNodes={setNodes}/>{!template&&<p>Nenhum modelo disponível para suas permissões atuais.</p>}{template&&<div className="access-actions"><button disabled={state.busy||!template.can_download} onClick={()=>void state.download(template,nodes)}>Baixar modelo oficial</button><button disabled={state.busy||!template.can_export} onClick={()=>setExporting(true)}>Exportar dados</button></div>}{state.catalog.items.some(t=>t.can_import)&&<UploadForm busy={state.busy} onUpload={state.upload}/>}</>}{state.preview&&<><ImportPreview preview={state.preview} rows={state.rows} issues={state.issues} busy={state.busy} onRows={p=>void state.rowsPage(p)} onIssues={p=>void state.issuesPage(p)}/>{canConfirm&&<button disabled={state.busy} onClick={()=>setConfirm(true)}>Revisar e confirmar importação</button>}</>}{state.history&&<ImportHistory data={state.history} busy={state.busy} onInspect={id=>void state.inspect(id)} onPage={p=>void state.historyPage(p)}/>} {confirm&&canConfirm&&state.preview&&<ConfirmImportDialog preview={state.preview} busy={state.busy} onClose={()=>setConfirm(false)} onConfirm={()=>{void state.confirm().then(()=>setConfirm(false));}}/>}{exporting&&template&&<ExportDialog template={template} busy={state.busy} onClose={()=>setExporting(false)} onExport={()=>{void state.exportWorkbook(template,nodes).then(()=>setExporting(false));}}/>}</section>;}
