import { StrictMode, useState } from 'react';
import { ApiClient } from '../api/client';
import { AuthContext } from '../auth/state';
import { Context } from '../platform/state';
import PrivilegedProvider from './PrivilegedProvider';
import { usePrivileged } from './state';
import { act, cleanup, fireEvent, render, screen, within, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import App from '../App';
const grant = { id: 'grant-a', context_id: 'privileged-a', parent_context_id: 'parent-a', tenant_id: 'tenant-a', contract_id: 'contract-a', tenant_name: 'Empresa A', contract_code: 'CTR-A', environment: 'TEST', operator: { user_id: 'operator', display_name: 'Administrador real', platform_role: 'PLATFORM_ADMIN' }, grant_type: 'FINANCIAL_FISCAL', status: 'ACTIVE', version: 1, reason: 'Investigar divergência financeira', reference: null, started_at: '2026-10-03T12:00:00Z', expires_at: '2099-01-01T00:00:00Z', ended_at: null, revoked_at: null, scopes: [] };
let role = 'PLATFORM_ADMIN', active = false, restoreStatus = 200, endStatus = 204;
const calls: {
    path: string;
    init: RequestInit;
}[] = [];
function response(data: unknown, status = 200) { return status === 204 ? new Response(null, { status }) : new Response(JSON.stringify(data), { status }); }
beforeEach(() => { sessionStorage.clear(); localStorage.clear(); sessionStorage.setItem('hiatlas.access-context.v1', 'parent-a'); role = 'PLATFORM_ADMIN'; active = false; restoreStatus = 200; endStatus = 204; calls.length = 0; vi.stubGlobal('fetch', vi.fn(async (url: string, init: RequestInit = {}) => { const path = url.replace('/api', ''); calls.push({ path, init }); if (path === '/auth/me')
    return response({ user_id: 'operator', display_name: 'Administrador real', platform_role: role }); if (path === '/auth/csrf')
    return response({ token: 'csrf' }); if (path === '/auth/reauthenticate')
    return response(null, 204); if (path === '/context')
    return response({ id: 'parent-a', tenant_name: 'Empresa A', contract_id: 'contract-a', contract_code: 'CTR-A', environment: 'TEST', expires_at: '2099-01-01T00:00:00Z', capabilities: ['memberships.read', 'grants.request', 'grants.read', 'grants.end'], privileged_context_id: active ? 'privileged-a' : null }); if (path.startsWith('/memberships?'))
    return response({ items: [], total: 0, limit: 20, offset: 0 }); if (path === '/grants' && init.method === 'POST') {
    active = true;
    return response(grant, 201);
} if (path === '/grants/context')
    return response(grant, restoreStatus); if (path === '/grants/grant-a/end') {
    if (endStatus === 204)
        active = false;
    return response(null, endStatus);
} if (path === '/grants/maintenance-actions')
    return response({ items: [] }); if (path.startsWith('/grants?'))
    return response({ items: [], total: 0, limit: 20, offset: 0 }); if (path.startsWith('/contracts'))
    return response({ items: [] }); return response({}, 404); })); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); vi.useRealTimers(); });
async function open() { render(<App />); fireEvent.click(await screen.findByRole('button', { name: 'Acessos Temporários' })); await screen.findByRole('heading', { name: 'Acessos Temporários' }); }
async function start() { await open(); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'synthetic-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); fireEvent.click(await screen.findByRole('button', { name: 'Confirmar acesso temporário' })); await screen.findByRole('region', { name: 'Acesso temporário privilegiado' }); }
it('admin has contextual area and empty production maintenance registry', async () => { await open(); expect(await screen.findByText('Nenhuma operação de manutenção está disponível nesta versão.')).toBeVisible(); expect(screen.getByText('Nenhuma concessão registrada neste contexto.')).toBeVisible(); });
it('support never sees privileged menu', async () => { role = 'PLATFORM_SUPPORT'; render(<App />); await screen.findByRole('heading', { name: 'Suporte HiAtlas' }); expect(screen.queryByRole('button', { name: 'Acessos Temporários' })).not.toBeInTheDocument(); });
it('requires justification and reauth before contextual review then binds explicit parent', async () => { await start(); const auth = calls.find(c => c.path === '/auth/reauthenticate')!; expect(JSON.parse(String(auth.init.body))).toEqual({ password: 'synthetic-password' }); const create = calls.find(c => c.path === '/grants' && c.init.method === 'POST')!; expect(JSON.parse(String(create.init.body))).toEqual({ grant_type: 'FINANCIAL_FISCAL', reason: grant.reason, reference: null, scopes: [] }); expect(new Headers(create.init.headers).get('X-HiAtlas-Context')).toBe('parent-a'); expect(String(create.init.body)).not.toContain('password'); });
it('banner preserves real operator and does not create operational data', async () => { await start(); const banner = screen.getByRole('region', { name: 'Acesso temporário privilegiado' }); expect(banner).toHaveFocus(); expect(banner).toHaveTextContent('ACESSO TEMPORÁRIO — FINANCEIRO/FISCAL'); expect(banner).toHaveTextContent('Administrador real'); expect(banner).toHaveTextContent('Empresa A'); expect(banner).toHaveTextContent('CTR-A'); expect(screen.getByText('Módulo operacional ainda indisponível.')).toBeVisible(); expect(screen.queryByRole('button', { name: 'Usuários' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Trocar empresa/contrato' })).not.toBeInTheDocument(); });
it('persists only opaque derived context and restores using child header', async () => { active = true; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); render(<App />); await screen.findByRole('region', { name: 'Acesso temporário privilegiado' }); expect(new Headers(calls.find(c => c.path === '/grants/context')!.init.headers).get('X-HiAtlas-Context')).toBe('privileged-a'); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBe('privileged-a'); expect(JSON.stringify({ ...sessionStorage })).not.toContain(grant.reason); expect(localStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); });
it('ends only after committed server response and restores normal portal focus', async () => { await start(); fireEvent.click(screen.getByRole('button', { name: 'Encerrar acesso temporário' })); expect(screen.getByRole('dialog')).toHaveTextContent('CTR-A'); fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Confirmar encerramento' })); const heading = await screen.findByRole('heading', { name: 'Administração HiAtlas' }); await waitFor(() => expect(heading).toHaveFocus()); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); expect(JSON.parse(String(calls.find(c => c.path === '/grants/grant-a/end')!.init.body))).toEqual({ expected_version: 1 }); });
it('revoked restore discards privileged state and returns safe picker', async () => { active = true; restoreStatus = 403; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); render(<App />); await screen.findByRole('heading', { name: 'Selecionar ambiente' }); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); expect(screen.queryByText(grant.reason)).not.toBeInTheDocument(); });
it('failed end keeps mode and accessible error inside confirmation', async () => { await start(); endStatus = 503; fireEvent.click(screen.getByRole('button', { name: 'Encerrar acesso temporário' })); fireEvent.click(screen.getByRole('button', { name: 'Confirmar encerramento' })); expect(await within(screen.getByRole('dialog')).findByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível'); expect(screen.getByRole('region', { name: 'Acesso temporário privilegiado' })).toBeVisible(); });
it('successful logout removes privileged context before new login', async () => { await start(); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/auth/logout' ? Promise.resolve(response(null, 204)) : original(url, init))); fireEvent.click(screen.getByRole('button', { name: 'Sair' })); await screen.findByRole('heading', { name: 'Bem-vindo à HiAtlas' }); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); });
it('justification and password are required and escape closes with focus return', async () => { await open(); const trigger = screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' }); trigger.focus(); fireEvent.click(trigger); expect(screen.getByRole('button', { name: 'Reautenticar e revisar' })).toBeDisabled(); expect(screen.getByLabelText('Motivo do acesso temporário')).toHaveFocus(); fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' }); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); expect(trigger).toHaveFocus(); });
it('denied reauthentication clears password and never requests grant', async () => { await open(); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/auth/reauthenticate' ? Promise.resolve(response({}, 403)) : original(url, init))); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'rejected-secret' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Acesso negado'); expect(screen.getByLabelText('Confirme sua senha')).toHaveValue(''); expect(calls.some(c => c.path === '/grants' && c.init.method === 'POST')).toBe(false); });
it('reload never emits create or reauth and preserves exact server expiry', async () => { active = true; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); render(<App />); await screen.findByRole('region', { name: 'Acesso temporário privilegiado' }); expect(screen.getByText(new Date(grant.expires_at).toLocaleString('pt-BR',{timeZoneName:'short'}))).toHaveAttribute('datetime', grant.expires_at); expect(calls.some(c => c.path === '/auth/reauthenticate' || c.path === '/grants' && c.init.method === 'POST')).toBe(false); });
it('normal context never inherits privilege merely from admin login', async () => { render(<App />); await screen.findByRole('heading', { name: 'Administração HiAtlas' }); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); expect(calls.some(c => c.path === '/grants/context')).toBe(false); });
it('late grant restore cannot repopulate interface after parent revocation', async () => { active = true; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); const original = fetch; let finish: ((value: Response) => void) | undefined, signal: AbortSignal | undefined; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => { if (url === '/api/grants/context') {
    signal = init?.signal ?? undefined;
    return new Promise<Response>(resolve => { finish = resolve; });
} return original(url, init); })); render(<App />); await waitFor(() => expect(finish).toBeDefined()); vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/context' ? Promise.resolve(response({ code: 'CONTEXT_INVALID' }, 403)) : original(url, init))); fireEvent(window, new Event('focus')); await screen.findByRole('heading', { name: 'Selecionar ambiente' }); expect(signal?.aborted).toBe(true); finish!(response(grant)); await Promise.resolve(); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); expect(screen.getByText(/Acesso temporário encerrado, expirado ou revogado/)).toHaveAttribute('role', 'status'); });
it('light and dark controls preserve privileged identity and mode', async () => { await start(); fireEvent.click(screen.getByRole('button', { name: 'Tema escuro' })); expect(screen.getByRole('main')).toHaveAttribute('data-theme', 'dark'); expect(screen.getByRole('region', { name: 'Acesso temporário privilegiado' })).toHaveTextContent('Administrador real'); fireEvent.click(screen.getByRole('button', { name: 'Tema claro' })); expect(screen.getByRole('main')).toHaveAttribute('data-theme', 'light'); expect(screen.getByRole('timer')).not.toHaveAttribute('aria-live'); });
it('countdown uses server deadline and expiry removes privileges without renewal polling', async () => { await start(); const original = fetch; const expires = new Date(Date.now() + 2500).toISOString(); vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/grants/context' ? Promise.resolve(response({ ...grant, expires_at: expires })) : original(url, init))); vi.useFakeTimers(); try {
    await act(async () => { fireEvent(window, new Event('focus')); await Promise.resolve(); });
    expect(screen.getByRole('timer')).toHaveTextContent('0:03');
    const reads = calls.filter(c => c.path === '/grants/context').length;
    await act(async () => { await vi.advanceTimersByTimeAsync(1000); });
    expect(screen.getByRole('timer')).toHaveTextContent('0:02');
    expect(calls.filter(c => c.path === '/grants/context')).toHaveLength(reads);
    await act(async () => { await vi.advanceTimersByTimeAsync(1600); });
    expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument();
    expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull();
    expect(screen.getByText(/Acesso temporário encerrado, expirado ou revogado/)).toHaveAttribute('role', 'status');
}
finally {
    vi.useRealTimers();
} });
it('reauth review shows actual operator and scoped company contract environment', async () => { await open(); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'synthetic-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); await screen.findByRole('button', { name: 'Confirmar acesso temporário' }); const dialog = screen.getByRole('dialog'); for (const value of ['Administrador real', 'Empresa A', 'CTR-A', 'Teste', grant.reason])
    expect(dialog).toHaveTextContent(value); expect(screen.queryByLabelText('Confirme sua senha')).not.toBeInTheDocument(); });
it('server rejects new grant with stale reauth and UI requires password again', async () => { await open(); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/grants' && init?.method === 'POST' ? Promise.resolve(response({ code: 'REAUTH_REQUIRED' }, 403)) : original(url, init))); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'synthetic-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); fireEvent.click(await screen.findByRole('button', { name: 'Confirmar acesso temporário' })); expect(await screen.findByRole('alert')).toHaveTextContent('Acesso negado'); expect(screen.getByLabelText('Confirme sua senha')).toHaveValue(''); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); });
it('wrong operator or contract on restored server projection fails closed', async () => { active = true; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/grants/context' ? Promise.resolve(response({ ...grant, contract_id: 'contract-b', operator: { ...grant.operator, user_id: 'other' } })) : original(url, init))); render(<App />); await screen.findByRole('heading', { name: 'Selecionar ambiente' }); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); expect(screen.queryByText(grant.reason)).not.toBeInTheDocument(); });
it('read-only support discovery never exposes temporary access escalation', async () => { const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => { if (url === '/api/context')
    return Promise.resolve(response({ id: 'parent-a', tenant_name: 'Empresa A', contract_id: 'contract-a', contract_code: 'CTR-A', environment: 'TEST', expires_at: '2099-01-01T00:00:00Z', capabilities: [], support_session_id: 'support-a' })); if (url === '/api/support-sessions/support-a')
    return response({ id: 'support-a', context_id: 'support-child', parent_context_id: 'parent-a', contract_id: 'contract-a', operator: { user_id: 'operator', display_name: 'Administrador real', platform_role: 'PLATFORM_ADMIN' }, viewed: { display_name: 'Pessoa visualizada', role_name: 'Comprador' }, mode: 'READ_ONLY', status: 'ACTIVE', expires_at: '2099-01-01T00:00:00Z' }); if (url.endsWith('/workspace'))
    return response({ effective_access: { read_only: true, capabilities: [] }, modules: [] }); return original(url, init); })); render(<App />); await screen.findByRole('region', { name: 'Sessão de suporte somente leitura' }); expect(screen.queryByRole('button', { name: 'Acessos Temporários' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })).not.toBeInTheDocument(); expect(calls.some(c => c.path.startsWith('/grants'))).toBe(false); });
it('HTTP session expired on privileged restore requires new login and removes opaque child', async () => { active = true; restoreStatus = 401; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); render(<App />); await screen.findByRole('heading', { name: 'Bem-vindo à HiAtlas' }); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); });
it('ambiguous create response recovers committed grant through parent discovery', async () => { await open(); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => { if (url === '/api/grants' && init?.method === 'POST') {
    active = true;
    return Promise.resolve(response({}, 503));
} return original(url, init); })); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'synthetic-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); fireEvent.click(await screen.findByRole('button', { name: 'Confirmar acesso temporário' })); await screen.findByRole('region', { name: 'Acesso temporário privilegiado' }); expect(screen.queryByRole('button', { name: 'Usuários' })).not.toBeInTheDocument(); });
it('discovery hides normal tools immediately while child validation is pending', async () => {
    // The menu commit precedes passive effect installation. Flush those effects before
    // dispatching the browser focus event, so this tests discovery rather than an event
    // sent before the contextual focus listener exists.
    await act(async () => { render(<App />); });
    await screen.findByRole('button', {name:'Acessos Temporários'});
    active=true;
    const readsBeforeFocus=calls.filter(call=>call.path==='/context').length;
    const original=fetch;
    let finish:((value:Response)=>void)|undefined;
    let childContext:string|null=null;
    vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{
        if(url==='/api/grants/context'){
            childContext=new Headers(init?.headers).get('X-HiAtlas-Context');
            return new Promise<Response>(resolve=>{finish=resolve;});
        }
        return original(url,init);
    }));
    await act(async()=>{fireEvent(window,new Event('focus'));});
    expect(calls.filter(call=>call.path==='/context').length).toBeGreaterThan(readsBeforeFocus);
    await waitFor(()=>expect(finish).toBeDefined());
    expect(childContext).toBe('privileged-a');
    expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button',{name:'Trocar empresa/contrato'})).not.toBeInTheDocument();
    await act(async()=>{finish!(response(grant));});
    await screen.findByRole('region',{name:'Acesso temporário privilegiado'});
});
it('end denied by server discards revoked context instead of restoring privileges locally', async () => { await start(); endStatus = 403; fireEvent.click(screen.getByRole('button', { name: 'Encerrar acesso temporário' })); fireEvent.click(screen.getByRole('button', { name: 'Confirmar encerramento' })); await screen.findByRole('heading', { name: 'Selecionar ambiente' }); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); });
it('version conflict reports 409 and retains server-authorized temporary mode', async () => { await start(); endStatus = 409; fireEvent.click(screen.getByRole('button', { name: 'Encerrar acesso temporário' })); fireEvent.click(screen.getByRole('button', { name: 'Confirmar encerramento' })); expect(await within(screen.getByRole('dialog')).findByRole('alert')).toHaveTextContent('Os dados foram alterados'); expect(screen.getByRole('region', { name: 'Acesso temporário privilegiado' })).toBeVisible(); });
it('parent expiry preserves terminal notice and child observation even without storage', async () => { const expires = new Date(Date.now() + 30000).toISOString(); const original = fetch; let parentExpiry: (() => void) | undefined, observations = 0; const timeout = window.setTimeout; vi.spyOn(window, 'setTimeout').mockImplementation((handler, ms, ...args) => { if (!parentExpiry && ms && ms > 29000 && ms < 31000 && typeof handler === 'function')
    parentExpiry = () => handler(...args); return timeout(handler, ms, ...args); }); vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => { if (url === '/api/context')
    return Promise.resolve(response({ id: 'parent-a', tenant_name: 'Empresa A', contract_id: 'contract-a', contract_code: 'CTR-A', environment: 'TEST', expires_at: expires, capabilities: ['memberships.read', 'grants.request', 'grants.read'], privileged_context_id: null })); if (url === '/api/grants' && init?.method === 'POST')
    return Promise.resolve(response({ ...grant, expires_at: expires }, 201)); if (url === '/api/grants/context') {
    observations++;
    return Promise.resolve(response({}, 403));
} return original(url, init); })); await open(); vi.stubGlobal('sessionStorage', { getItem: () => { throw new Error('unavailable'); }, setItem: () => { throw new Error('unavailable'); }, removeItem: () => { throw new Error('unavailable'); } }); fireEvent.click(screen.getByRole('button', { name: 'Solicitar acesso Financeiro/Fiscal' })); fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'), { target: { value: grant.reason } }); fireEvent.change(screen.getByLabelText('Confirme sua senha'), { target: { value: 'synthetic-password' } }); fireEvent.click(screen.getByRole('button', { name: 'Reautenticar e revisar' })); fireEvent.click(await screen.findByRole('button', { name: 'Confirmar acesso temporário' })); await screen.findByRole('region', { name: 'Acesso temporário privilegiado' }); expect(parentExpiry).toBeDefined(); await act(async () => { parentExpiry!(); await Promise.resolve(); }); expect(screen.getByText(/Acesso temporário encerrado, expirado ou revogado/)).toHaveAttribute('role', 'status'); expect(observations).toBe(1); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); });
it('two independent tab flows keep normal tab normal and ending one does not elevate the other', async () => {
    const original = fetch;
    vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => { const scope = new Headers(init?.headers).get('X-HiAtlas-Context'); if (url === '/api/grants' && init?.method === 'POST')
        return Promise.resolve(response({ ...grant, id: scope === 'parent-b' ? 'grant-b' : 'grant-a', parent_context_id: scope, context_id: scope === 'parent-b' ? 'privileged-b' : 'privileged-a' }, 201)); if (url === '/api/grants/grant-a/end' || url === '/api/grants/grant-b/end')
        return Promise.resolve(response(null, 204)); return original(url, init); }));
    function Probe({ name }: {
        name: string;
    }) { const state = usePrivileged()!; return <section data-testid={name}><span>{state.grant ? `privileged ${state.grant.context_id}` : 'normal'}</span><button onClick={() => void state.start(grant.reason, null)}>start {name}</button><button onClick={() => void state.end()}>end {name}</button></section>; }
    function Flow({ name }: {
        name: string;
    }) { const [api] = useState(() => new ApiClient()); return <AuthContext.Provider value={{ api, user: { user_id: 'operator', display_name: 'Administrador real', platform_role: 'PLATFORM_ADMIN' }, loading: false, busy: false, error: null, login: async () => { }, logout: async () => { }, retry: () => { } }}><Context.Provider value={{ selected: { id: `parent-${name}`, tenant_name: 'Empresa A', contract_id: 'contract-a', contract_code: 'CTR-A', environment: 'TEST', expires_at: grant.expires_at, capabilities: ['grants.request'] }, loading: false, busy: false, error: null, recovering: false, select: async () => { }, clear: async () => { }, retry: () => { } }}><PrivilegedProvider><Probe name={name}/></PrivilegedProvider></Context.Provider></AuthContext.Provider>; }
    render(<><Flow name="a"/><Flow name="b"/></>);
    const a = within(screen.getByTestId('a')), b = within(screen.getByTestId('b'));
    fireEvent.click(a.getByRole('button', { name: 'start a' }));
    await a.findByText('privileged privileged-a');
    expect(b.getByText('normal')).toBeVisible();
    fireEvent.click(b.getByRole('button', { name: 'start b' }));
    await b.findByText('privileged privileged-b');
    fireEvent.click(a.getByRole('button', { name: 'end a' }));
    await a.findByText('normal');
    expect(b.getByText('privileged privileged-b')).toBeVisible();
});
it('restore rejects mismatched derived context projection', async () => { active = true; sessionStorage.setItem('hiatlas.privileged-context.v1', 'privileged-a'); const original = fetch; vi.stubGlobal('fetch', vi.fn((url: string, init?: RequestInit) => url === '/api/grants/context' ? Promise.resolve(response({ ...grant, context_id: 'unexpected-child' })) : original(url, init))); render(<App />); await screen.findByRole('heading', { name: 'Selecionar ambiente' }); expect(screen.queryByRole('region', { name: 'Acesso temporário privilegiado' })).not.toBeInTheDocument(); expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull(); });

it('temporary restore failure keeps banner but hides workspace and exposes retry',async()=>{await start();const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/grants/context'?Promise.resolve(response({},503)):original(url,init)));fireEvent(window,new Event('focus'));expect(await screen.findByRole('button',{name:'Validar acesso temporário novamente'})).toBeVisible();expect(screen.getByRole('region',{name:'Acesso temporário privilegiado'})).toBeVisible();expect(screen.queryByText('Módulo operacional ainda indisponível.')).not.toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível');});
it('wrong password during reauthentication reports AUTH_INVALID without logging out valid operator',async()=>{await open();const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/auth/reauthenticate'?Promise.resolve(response({code:'AUTH_INVALID'},401)):original(url,init)));fireEvent.click(screen.getByRole('button',{name:'Solicitar acesso Financeiro/Fiscal'}));fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'),{target:{value:grant.reason}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'wrong-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));expect(await within(screen.getByRole('dialog')).findByRole('alert')).toHaveTextContent('E-mail ou senha inválidos');expect(screen.getByRole('heading',{name:'Administração HiAtlas'})).toBeInTheDocument();expect(sessionStorage.getItem('hiatlas.access-context.v1')).toBe('parent-a');expect(screen.getByLabelText('Confirme sua senha')).toHaveValue('');expect(calls.some(c=>c.path==='/grants'&&c.init.method==='POST')).toBe(false);});
it('SESSION_INVALID during reauthentication still clears actual expired authentication',async()=>{await open();const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/auth/reauthenticate'?Promise.resolve(response({code:'SESSION_INVALID'},401)):original(url,init)));fireEvent.click(screen.getByRole('button',{name:'Solicitar acesso Financeiro/Fiscal'}));fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'),{target:{value:grant.reason}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'synthetic-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));await screen.findByRole('heading',{name:'Bem-vindo à HiAtlas'});expect(sessionStorage.getItem('hiatlas.access-context.v1')).toBeNull();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();});
it('ambiguous committed creation and unavailable parent stay closed until authoritative retry',async()=>{await open();const original=fetch;let parentUnavailable=true;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/grants'&&init?.method==='POST'){active=true;return Promise.resolve(response({},503));}if(url==='/api/context'&&active&&parentUnavailable)return Promise.resolve(response({},503));return original(url,init);}));fireEvent.click(screen.getByRole('button',{name:'Solicitar acesso Financeiro/Fiscal'}));fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'),{target:{value:grant.reason}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'synthetic-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));fireEvent.click(await screen.findByRole('button',{name:'Confirmar acesso temporário'}));const retry=await screen.findByRole('button',{name:'Validar acesso temporário novamente'});expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Trocar empresa/contrato'})).not.toBeInTheDocument();parentUnavailable=false;fireEvent.click(retry);await screen.findByRole('region',{name:'Acesso temporário privilegiado'});expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBe('privileged-a');});
it('aborted committed creation after failed logout reconciles instead of returning unknown normal mode',async()=>{await open();const original=fetch;let finish:((value:Response)=>void)|undefined,parentUnavailable=true;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/grants'&&init?.method==='POST'){active=true;return new Promise<Response>(resolve=>{finish=resolve;});}if(url==='/api/auth/logout')return Promise.resolve(response({},503));if(url==='/api/context'&&active&&parentUnavailable)return Promise.resolve(response({},503));return original(url,init);}));fireEvent.click(screen.getByRole('button',{name:'Solicitar acesso Financeiro/Fiscal'}));fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'),{target:{value:grant.reason}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'synthetic-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));fireEvent.click(await screen.findByRole('button',{name:'Confirmar acesso temporário'}));await waitFor(()=>expect(finish).toBeDefined());fireEvent.click(screen.getByRole('button',{name:'Sair'}));await waitFor(()=>expect(screen.getAllByRole('alert').length).toBeGreaterThan(0));finish!(response(grant,201));const retry=await screen.findByRole('button',{name:'Validar acesso temporário novamente'});expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();parentUnavailable=false;fireEvent.click(retry);await screen.findByRole('region',{name:'Acesso temporário privilegiado'});});
it('StrictMode effect replay keeps reauthentication request live and permits correction before grant review',async()=>{const original=fetch;let rejected=true;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/auth/reauthenticate'&&rejected?Promise.resolve(response({code:'AUTH_INVALID'},401)):original(url,init)));render(<StrictMode><App/></StrictMode>);fireEvent.click(await screen.findByRole('button',{name:'Acessos Temporários'}));fireEvent.click(await screen.findByRole('button',{name:'Solicitar acesso Financeiro/Fiscal'}));fireEvent.change(screen.getByLabelText('Motivo do acesso temporário'),{target:{value:grant.reason}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'wrong-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));expect(await within(screen.getByRole('dialog')).findByRole('alert')).toHaveTextContent('E-mail ou senha inválidos');expect(screen.getByLabelText('Confirme sua senha')).toHaveValue('');rejected=false;fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'synthetic-password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));fireEvent.click(await screen.findByRole('button',{name:'Confirmar acesso temporário'}));await screen.findByRole('region',{name:'Acesso temporário privilegiado'});expect(calls.some(c=>c.path==='/auth/reauthenticate')).toBe(true);expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBe('privileged-a');});