/** Fictional sample data for the HiAtlas navigable prototype. */
export type ModuleKey = 'dashboard' | 'compras' | 'comex' | 'estoque' | 'financeiro' | 'datahub' | 'agenda' | 'relatorios' | 'administracao';
export const modules: { id: ModuleKey; label: string; icon: string; children: string[] }[] = [
  { id: 'dashboard', label: 'Dashboard', icon: '◫', children: [] },
  { id: 'compras', label: 'Compras', icon: '⇄', children: ['Nacional', 'Internacional', 'Sugestão de Compra', 'Cotações', 'Fornecedores', 'Aprovações'] },
  { id: 'comex', label: 'Importação / COMEX', icon: '◈', children: ['Processos', 'Proformas', 'Bookings', 'Containers', 'Navios', 'Portos', 'Desembaraço', 'Entrega / Devolução'] },
  { id: 'estoque', label: 'Estoque', icon: '▤', children: ['Produtos', 'Lojas', 'Centros de Distribuição', 'Depósitos', 'Movimentações', 'Cobertura', 'Necessidade de Compra'] },
  { id: 'financeiro', label: 'Financeiro', icon: '◉', children: ['Adiantamentos', 'Saldo', 'Numerário', 'Câmbio', 'Custos'] },
  { id: 'datahub', label: 'Data Hub', icon: '⌘', children: ['Excel', 'APIs', 'Integrações', 'Mapeamentos', 'Validação', 'Sincronizações'] },
  { id: 'agenda', label: 'Agenda', icon: '▦', children: [] },
  { id: 'relatorios', label: 'Relatórios', icon: '▥', children: [] },
  { id: 'administracao', label: 'Administração', icon: '⚙', children: ['Usuários', 'Perfis e permissões', 'Unidades', 'Configurações'] },
];
export const moduleCatalog = modules;
const allModules = modules.map(({ id }) => id);
export const profiles: { id: string; name: string; code: string; modules: ModuleKey[] }[] = [
  { id: 'coordenacao', name: 'Coordenação', code: 'CO', modules: allModules.filter(id => id !== 'administracao') },
  { id: 'supervisao', name: 'Supervisão', code: 'SU', modules: ['dashboard', 'compras', 'comex', 'estoque', 'agenda', 'relatorios'] },
  { id: 'comprador-nacional', name: 'Comprador nacional', code: 'CN', modules: ['dashboard', 'compras', 'estoque', 'agenda', 'relatorios'] },
  { id: 'comprador-internacional', name: 'Comprador internacional', code: 'CI', modules: ['dashboard', 'compras', 'comex', 'estoque', 'agenda', 'relatorios'] },
  { id: 'financeiro', name: 'Financeiro', code: 'FI', modules: ['dashboard', 'financeiro', 'comex', 'agenda', 'relatorios'] },
  { id: 'administrador', name: 'Administrador', code: 'AD', modules: [...allModules] },
  { id: 'diretoria', name: 'Diretoria', code: 'DI', modules: allModules.filter(id => id !== 'administracao' && id !== 'datahub') },
  { id: 'loja', name: 'Loja', code: 'LJ', modules: ['dashboard', 'estoque', 'agenda', 'relatorios'] },
  { id: 'cd', name: 'Centro de distribuição', code: 'CD', modules: ['dashboard', 'estoque', 'comex', 'agenda', 'relatorios'] },
];
export type DemoRecord = { id: string; title: string; module: ModuleKey; section: string; company: string; unit: string; status: 'Crítico' | 'Atenção' | 'Em dia'; owner: string; due: string; value: string; detail: string };
type Sample = [ModuleKey, string, string, string, string];
const samples: Sample[] = [
  ['dashboard', '', 'Reposição de embalagens em risco', '6 dias', 'Cobertura abaixo da meta de 15 dias; avaliar antecipação de compra.'],
  ['dashboard', '', 'Chegada de componentes confirmada', '2 contêineres', 'Recebimento previsto no CD Sul; reservar doca para conferência.'],
  ['compras', 'Nacional', 'Pedido de caixas reforçadas', 'R$ 28.400', '4.000 caixas; fornecedor Embalagens Serra; condição de pagamento em 30 dias.'],
  ['compras', 'Nacional', 'Reposição de filme stretch', 'R$ 12.750', '150 bobinas; entrega parcial de 60 unidades disponível.'],
  ['compras', 'Internacional', 'Aquisição de rolamentos industriais', 'US$ 42.600', '1.200 peças; cotação FOB; lead time estimado de 45 dias.'],
  ['compras', 'Internacional', 'Pedido de sensores de temperatura', 'US$ 18.900', '350 sensores; amostra técnica aguardando validação de engenharia.'],
  ['compras', 'Sugestão de Compra', 'Repor luvas de proteção', '600 pares', 'Demanda semanal de 140 pares; estoque disponível de 180 pares.'],
  ['compras', 'Sugestão de Compra', 'Antecipar compra de etiquetas', '90 rolos', 'Campanha sazonal amplia consumo; sugestão considera estoque de segurança.'],
  ['compras', 'Cotações', 'Comparativo de paletes tratados', '3 propostas', 'Menor preço de R$ 84 por unidade; comparar frete e prazo de entrega.'],
  ['compras', 'Cotações', 'Frete de peças importadas', '2 propostas', 'Comparação entre embarque consolidado e contêiner exclusivo.'],
  ['compras', 'Fornecedores', 'Embalagens Serra — homologação', '92% aderência', 'Certificado de qualidade recebido; cadastro bancário pendente de revisão.'],
  ['compras', 'Fornecedores', 'Componentes Vale — desempenho', '97% no prazo', 'Doze entregas avaliadas; uma ocorrência de divergência de quantidade.'],
  ['compras', 'Aprovações', 'Liberar compra de motores', 'R$ 68.200', 'Solicitação acima da alçada do comprador; requer revisão da coordenação.'],
  ['compras', 'Aprovações', 'Aprovar reajuste de embalagens', '4,2%', 'Reajuste proposto para próximo pedido; histórico comparativo disponível.'],
  ['comex', 'Processos', 'IMP-026 — linha de transmissão', 'US$ 86.400', 'Processo marítimo; documentação comercial em conferência antes do embarque.'],
  ['comex', 'Processos', 'IMP-031 — sensores de pressão', 'US$ 24.800', 'Processo aéreo; chegada estimada e coleta local alinhadas.'],
  ['comex', 'Proformas', 'PF-204 — válvulas industriais', 'US$ 31.500', 'Conferir Incoterm FOB e dados do beneficiário antes do aceite.'],
  ['comex', 'Proformas', 'PF-219 — correias técnicas', 'US$ 14.700', 'Revisão recebida com redução da quantidade mínima para 500 peças.'],
  ['comex', 'Bookings', 'Reserva marítima — componentes', '2 × 40 HC', 'Janela de embarque confirmada; instrução de embarque ainda pendente.'],
  ['comex', 'Bookings', 'Reserva consolidada — ferramentas', '8,4 m³', 'Carga LCL; prazo de entrega no armazém de consolidação termina hoje.'],
  ['comex', 'Containers', 'DEMO-CT01 — conferência de lacre', '40 HC', 'Lacre informado diverge do packing list; solicitar correção documental.'],
  ['comex', 'Containers', 'DEMO-CT02 — liberação de retirada', '20 GP', 'Carga disponível para agendamento de transporte ao centro de distribuição.'],
  ['comex', 'Navios', 'Navio fictício Aurora Mar', 'ETA em 3 dias', 'Escala de demonstração; revisar impacto da chegada na janela de recebimento.'],
  ['comex', 'Navios', 'Navio fictício Horizonte Azul', 'ETA amanhã', 'Escala de demonstração; acompanhamento de atracação previsto para manhã.'],
  ['comex', 'Portos', 'Santos — janela de coleta', '2 cargas', 'Exemplo de programação de retirada; confirmar disponibilidade do transportador.'],
  ['comex', 'Portos', 'Itapoá — armazenagem prevista', 'R$ 3.200', 'Estimativa demonstrativa de armazenagem; retirada planejada no primeiro período.'],
  ['comex', 'Desembaraço', 'IMP-026 — revisão documental', '1 pendência', 'Descrição de uma mercadoria precisa ser alinhada entre invoice e cadastro.'],
  ['comex', 'Desembaraço', 'IMP-031 — documentação completa', '7 documentos', 'Dossiê de exemplo conferido e pronto para próxima etapa operacional.'],
  ['comex', 'Entrega / Devolução', 'Devolver contêiner DEMO-CT02', '2 dias livres', 'Agendar devolução do equipamento vazio após descarga no CD Sul.'],
  ['comex', 'Entrega / Devolução', 'Receber lote de ferramentas', '18 paletes', 'Doca 3 reservada; equipe de conferência informada sobre descarga.'],
  ['estoque', 'Produtos', 'Rolamento 6205 — disponibilidade', '380 unidades', 'SKU DEMO-6205; 120 unidades reservadas e 260 disponíveis para atendimento.'],
  ['estoque', 'Produtos', 'Luva nitrílica — lote', '180 pares', 'SKU DEMO-LN; conferir lote e prazo de validade no próximo recebimento.'],
  ['estoque', 'Lojas', 'Loja Centro — reposição de EPIs', '42 itens', 'Separação de itens com saldo abaixo do mínimo para transferência.'],
  ['estoque', 'Lojas', 'Loja Centro — contagem cíclica', '96% acurácia', 'Diferença de oito unidades em conectores; recontagem solicitada.'],
  ['estoque', 'Centros de Distribuição', 'CD Sul — ocupação de posições', '78% ocupado', '156 de 200 posições utilizadas; capacidade disponível para próxima importação.'],
  ['estoque', 'Centros de Distribuição', 'CD Sul — fila de expedição', '12 pedidos', 'Quatro pedidos aguardam conferência; transportador programado para tarde.'],
  ['estoque', 'Depósitos', 'Depósito de quarentena — inspeção', '3 lotes', 'Materiais bloqueados por embalagem danificada aguardam avaliação.'],
  ['estoque', 'Depósitos', 'Depósito de peças — endereçamento', '24 posições', 'Nova faixa de endereços preparada para recebimento de componentes.'],
  ['estoque', 'Movimentações', 'Transferência TR-084 para loja', '120 peças', 'Saída registrada; confirmação do recebimento na unidade de destino pendente.'],
  ['estoque', 'Movimentações', 'Entrada NF demonstrativa 4501', '36 volumes', 'Conferência identificou uma caixa a menos que a quantidade prevista.'],
  ['estoque', 'Cobertura', 'Filme stretch — cobertura baixa', '5 dias', 'Consumo médio de 12 bobinas por dia; entrega prevista em sete dias.'],
  ['estoque', 'Cobertura', 'Conectores — cobertura adequada', '32 dias', 'Saldo cobre consumo projetado; próxima revisão de demanda em três dias.'],
  ['estoque', 'Necessidade de Compra', 'Caixas médias — demanda líquida', '2.400 unidades', 'Necessidade calculada após descontar saldo disponível e pedidos em trânsito.'],
  ['estoque', 'Necessidade de Compra', 'Correias — reposição preventiva', '180 peças', 'Ponto de pedido atingido; considerar lote mínimo de 200 peças.'],
  ['financeiro', 'Adiantamentos', 'Sinal PF-204 — válvulas', 'US$ 9.450', 'Parcela de 30% vinculada à proforma; dados de pagamento em revisão.'],
  ['financeiro', 'Adiantamentos', 'Adiantamento de frete local', 'R$ 2.800', 'Solicitação vinculada à retirada de carga; comprovante aguardando anexação.'],
  ['financeiro', 'Saldo', 'Saldo projetado de importações', 'R$ 214.500', 'Projeção demonstrativa desconta compromissos previstos para a semana.'],
  ['financeiro', 'Saldo', 'Reserva para fornecedores locais', 'R$ 86.200', 'Valor de exemplo separado para seis pagamentos aprovados.'],
  ['financeiro', 'Numerário', 'Numerário IMP-026', 'R$ 47.900', 'Estimativa de despesas do processo; revisão da memória de cálculo pendente.'],
  ['financeiro', 'Numerário', 'Complemento IMP-031', 'R$ 4.600', 'Diferença estimada de armazenagem e transporte após atualização operacional.'],
  ['financeiro', 'Câmbio', 'Cotação indicativa — PF-204', 'R$ 5,18 / US$', 'Taxa fictícia para simulação; comparar custo total com tarifas incluídas.'],
  ['financeiro', 'Câmbio', 'Simulação de fechamento — sensores', 'US$ 18.900', 'Cenário demonstrativo de liquidação em dois dias; sem contratação real.'],
  ['financeiro', 'Custos', 'Custo posto — rolamentos', 'R$ 82,40 / un.', 'Simulação incorpora mercadoria, frete e despesas rateadas por quantidade.'],
  ['financeiro', 'Custos', 'Variação logística — IMP-026', '+6,8%', 'Diferença entre orçamento e estimativa atual concentrada na armazenagem.'],
  ['datahub', 'Excel', 'Importar catálogo de produtos', '248 linhas', 'Planilha de exemplo; três códigos duplicados precisam de correção.'],
  ['datahub', 'Excel', 'Planilha de pedidos nacionais', '64 linhas', 'Colunas de fornecedor, quantidade e preço reconhecidas para prévia.'],
  ['datahub', 'APIs', 'Conector de estoque — sandbox', '120 registros', 'Resposta simulada; última consulta de demonstração concluída sem erro.'],
  ['datahub', 'APIs', 'Conector de pedidos — sandbox', '1 campo ausente', 'Payload de exemplo não inclui unidade de destino em um pedido.'],
  ['datahub', 'Integrações', 'ERP de demonstração — produtos', 'Simulada', 'Integração ilustrativa configurada para leitura de cadastros de produtos.'],
  ['datahub', 'Integrações', 'Logística de demonstração — eventos', 'Em revisão', 'Mapear eventos de chegada e entrega antes de habilitar o fluxo simulado.'],
  ['datahub', 'Mapeamentos', 'Mapeamento de SKU externo', '38 equivalências', 'Relacionar códigos do fornecedor aos códigos internos de produtos.'],
  ['datahub', 'Mapeamentos', 'Mapeamento de unidades', '3 vínculos', 'Matriz, Loja Centro e CD Sul associados aos identificadores de exemplo.'],
  ['datahub', 'Validação', 'Pedidos — unidade inexistente', '2 erros', 'Corrigir identificador de unidade na origem para liberar os registros.'],
  ['datahub', 'Validação', 'Produtos — cadastro consistente', '245 válidos', 'Amostra validada quanto a código, descrição e unidade de medida.'],
  ['datahub', 'Sincronizações', 'Sincronização simulada de saldos', '98% concluído', 'Dois itens aguardam resolução de conflito entre depósito e unidade.'],
  ['datahub', 'Sincronizações', 'Sincronização simulada de pedidos', '64 atualizados', 'Execução demonstrativa concluída; nenhum dado externo foi alterado.'],
  ['agenda', '', 'Reunião de alinhamento de importações', '09:30', 'Revisar documentos pendentes, reservas marítimas e previsão de chegada.'],
  ['agenda', '', 'Janela de recebimento no CD Sul', '14:00', 'Conferência de 18 paletes e liberação de equipamento após descarga.'],
  ['relatorios', '', 'Compras por fornecedor — amostra', 'R$ 428 mil', 'Relatório demonstrativo com distribuição de gastos e entregas no prazo.'],
  ['relatorios', '', 'Cobertura por unidade — amostra', '18 SKUs em atenção', 'Visão demonstrativa compara consumo médio, saldo e pedidos em trânsito.'],
  ['administracao', '', 'Revisão de acessos de demonstração', '9 perfis', 'Perfis ilustrativos para navegar pelas áreas do protótipo.'],
  ['administracao', '', 'Estrutura de unidades de exemplo', '3 unidades', 'Organização fictícia com matriz, loja e centro de distribuição.'],
  ['administracao', 'Usuários', 'Marina Costa — cadastro de exemplo', 'Coordenação', 'Pessoa fictícia; acesso demonstrativo às áreas operacionais.'],
  ['administracao', 'Usuários', 'Lucas Reis — cadastro de exemplo', 'Comprador nacional', 'Pessoa fictícia; perfil ilustrativo associado à Matriz.'],
  ['administracao', 'Perfis e permissões', 'Financeiro — revisão de acesso', '5 módulos', 'Escopo do protótipo inclui financeiro, COMEX, agenda, relatórios e dashboard.'],
  ['administracao', 'Perfis e permissões', 'Administrador — acesso de revisão', '9 módulos', 'Acesso completo para avaliação do protótipo; sem autorização de produção.'],
  ['administracao', 'Unidades', 'Matriz — configuração de exemplo', 'Administrativa', 'Unidade fictícia responsável pela coordenação de compras e financeiro.'],
  ['administracao', 'Unidades', 'CD Sul — configuração de exemplo', 'Logística', 'Unidade fictícia destinada a recebimento, armazenagem e expedição.'],
  ['administracao', 'Configurações', 'Meta de cobertura demonstrativa', '15 dias', 'Parâmetro ilustrativo utilizado para destacar necessidades de reposição.'],
  ['administracao', 'Configurações', 'Alçada de compra demonstrativa', 'R$ 50.000', 'Parâmetro ilustrativo para encaminhar pedidos à coordenação.'],
];
export const records: DemoRecord[] = samples.map(([module, section, title, value, detail], index) => ({
  id: `DEMO-${String(index + 1).padStart(3, '0')}`,
  title, module, section,
  company: index % 2 === 0 ? 'Aurora Distribuição' : 'Horizonte Industrial',
  unit: ['Matriz', 'Loja Centro', 'CD Sul'][index % 3],
  status: (['Crítico', 'Atenção', 'Em dia'] as const)[index % 3],
  owner: ['Marina Costa', 'Lucas Reis', 'Ana Martins', 'Pedro Lima'][index % 4],
  due: ['Hoje', 'Amanhã', 'Em 3 dias'][index % 3],
  value,
  detail: `Amostra fictícia. ${detail}`,
}));

