import * as React from 'react';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import App from '../App';
const session = { id:'support-a',context_id:'child-a',parent_context_id:'parent-a',tenant_id:'tenant-a',contract_id:'contract-a',tenant_name:'Empresa A',contract_code:'CTR-A',environment:'TEST',operator:{user_id:'operator',display_name:'Operador real',platform_role:'PLATFORM_SUPPORT'},viewed:{membership_id:'member-a',user_id:'customer',display_name:'Ana cliente',role_id:'buyer',role_name:'Comprador'},mode:'READ_ONLY',reason:'Investigar chamado',reference:null,started_at:'2026-10-02T12:00:00Z',expires_at:'2099-01-01T00:00:00Z',ended_at:null,status:'ACTIVE' };
const member={id:'member-a',user_id:'customer',display_name:'Ana cliente',email:'ana@example.test',role_id:'buyer',role_name:'Comprador',active:true,blocked:false,invitation_pending:false,version:1,allowed_actions:['start_support'],last_access_at:null,invitation_status:null};
const calls:{path:string;init:RequestInit}[]=[];
let active=false, endStatus=204, supportStatus=200, eligible=true;
function response(data:unknown,status=200){return status===204?new Response(null,{status}):new Response(JSON.stringify(data),{status});}
beforeEach(()=>{sessionStorage.clear();localStorage.clear();sessionStorage.setItem('hiatlas.access-context.v1','parent-a');active=false;endStatus=204;supportStatus=200;eligible=true;calls.length=0;vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit={})=>{const path=url.replace('/api','');calls.push({path,init});if(path==='/auth/me')return response({user_id:'operator',display_name:'Operador real',platform_role:'PLATFORM_SUPPORT'});if(path==='/auth/csrf')return response({token:'csrf'});if(path==='/context')return response({id:'parent-a',tenant_name:'Empresa A',contract_id:'contract-a',contract_code:'CTR-A',environment:'TEST',expires_at:'2099-01-01T00:00:00Z',capabilities:['memberships.read','support.session.start','support.history.read'],support_session_id:active?'support-a':null});if(path.startsWith('/contracts'))return response({items:[]});if(path.startsWith('/memberships?'))return response({items:[member],total:1,limit:20,offset:0});if(path==='/memberships/member-a')return response({...member,allowed_actions:eligible?['start_support']:[]});if(path==='/support-sessions'&&init.method==='POST'){active=true;return response(session,201);}if(path==='/support-sessions/support-a/end'){if(endStatus===204)active=false;return response({},endStatus);}if(path==='/support-sessions/support-a')return response(session,supportStatus);if(path.endsWith('/workspace'))return response({effective_access:{read_only:true,capabilities:[]},modules:[{code:'PROCUREMENT',label:'Compras',contracted:true,active:true,enabled:true,operational_available:false}]});if(path.startsWith('/support-sessions?'))return response({items:[],total:0,limit:20,offset:0});return response({},404);}));});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.useRealTimers();vi.unstubAllGlobals();});
async function start(){render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar início somente leitura'}));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});}
it('starts from a real member detail with required reason and explicit parent context',async()=>{render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));expect(screen.getByRole('dialog')).toHaveTextContent('Ana cliente');expect(screen.getByRole('button',{name:'Confirmar início somente leitura'})).toBeDisabled();fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});const call=calls.find(c=>c.path==='/support-sessions'&&c.init.method==='POST')!;expect(JSON.parse(String(call.init.body))).toEqual({membership_id:'member-a',reason:'Investigar chamado',reference:null,mode:'READ_ONLY'});expect(new Headers(call.init.headers).get('X-HiAtlas-Context')).toBe('parent-a');});
it('keeps operator, viewed user, role and context visible and removes management and switch',async()=>{await start();const banner=screen.getByRole('region',{name:'Sessão de suporte somente leitura'});for(const text of ['SESSÃO DE SUPORTE — SOMENTE LEITURA','Operador: Operador real','Usuário visualizado: Ana cliente','Perfil: Comprador','Empresa A','CTR-A','Teste'])expect(banner).toHaveTextContent(text);expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Trocar empresa/contrato'})).not.toBeInTheDocument();expect(await screen.findByText('Compras')).toBeVisible();expect(screen.getByText('Ambiente operacional indisponível')).toBeVisible();expect(new Headers(calls.find(c=>c.path.endsWith('/workspace'))?.init.headers).get('X-HiAtlas-Context')).toBe('child-a');});
it('stores only opaque support reference and revalidates auth parent and session on reload',async()=>{active=true;sessionStorage.setItem('hiatlas.support-session.v1','support-a');render(<App/>);expect(screen.queryByText('Ana cliente')).not.toBeInTheDocument();await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});expect(calls.map(c=>c.path).slice(0,3)).toEqual(['/auth/me','/context','/support-sessions/support-a']);expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBe('support-a');expect(localStorage.getItem('hiatlas.support-session.v1')).toBeNull();});
it('discovers interrupted start from validated parent instead of mounting parent management',async()=>{active=true;render(<App/>);await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});expect(calls.some(c=>c.path.startsWith('/memberships'))).toBe(false);});
it('server rejection on restore clears derived data and reference',async()=>{active=true;supportStatus=403;sessionStorage.setItem('hiatlas.support-session.v1','support-a');render(<App/>);await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();expect(screen.queryByText('Ana cliente')).not.toBeInTheDocument();});
it('failed end keeps banner and never claims normal management access',async()=>{await start();endStatus=503;fireEvent.click(screen.getByRole('button',{name:'Encerrar sessão de suporte'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar encerramento'}));await screen.findByText(/Serviço temporariamente indisponível/);expect(screen.getByRole('region',{name:'Sessão de suporte somente leitura'})).toBeVisible();expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();});
it('committed end clears reference and returns focus to the normal portal',async()=>{await start();fireEvent.click(screen.getByRole('button',{name:'Encerrar sessão de suporte'}));expect(screen.getByRole('dialog')).toHaveTextContent('Ana cliente');fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar encerramento'}));const heading=await screen.findByRole('heading',{name:'Suporte HiAtlas'});await waitFor(()=>expect(heading).toHaveFocus());expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();expect(screen.queryByRole('region',{name:'Sessão de suporte somente leitura'})).not.toBeInTheDocument();});
it('never offers start after live member eligibility is removed',async()=>{eligible=false;render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));await screen.findByText('Perfil: Comprador');expect(screen.queryByRole('button',{name:'Iniciar sessão de suporte'})).not.toBeInTheDocument();});
it('normal portal exposes bounded contextual support history',async()=>{render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Sessões de suporte'}));await screen.findByText('Nenhuma sessão de suporte registrada neste contexto.');expect(calls.some(c=>c.path==='/support-sessions?limit=20&offset=0')).toBe(true);});
it('failed start reports the server error without claiming active support',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/support-sessions'&&init?.method==='POST'?Promise.resolve(response({},503)):original(url,init)));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));expect(await screen.findByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível');expect(screen.queryByRole('region',{name:'Sessão de suporte somente leitura'})).not.toBeInTheDocument();expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();});
it('interrupted start revalidates parent discovery before allowing management after failed logout',async()=>{const original=fetch;let resolveStart:((value:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/support-sessions'&&init?.method==='POST'){active=true;return new Promise<Response>(resolve=>{resolveStart=resolve;});}if(url==='/api/auth/logout')return Promise.resolve(response({},503));return original(url,init);}));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));await waitFor(()=>expect(resolveStart).toBeDefined());fireEvent.click(screen.getByRole('button',{name:'Sair'}));await screen.findByText(/Serviço temporariamente indisponível/);resolveStart!(response(session,201));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();});
it('ambiguous start failure checks parent for a committed support session before showing tools',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/support-sessions'&&init?.method==='POST'){active=true;return Promise.resolve(response({},503));}return original(url,init);}));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();});
it('expired support reports a neutral accessible notice after discarding child content',async()=>{active=true;supportStatus=403;sessionStorage.setItem('hiatlas.support-session.v1','support-a');render(<App/>);await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(screen.getByText(/Sessão de suporte encerrada, expirada ou indisponível/)).toHaveAttribute('role','status');expect(screen.queryByText('Ana cliente')).not.toBeInTheDocument();});
it('ending restored support cannot resurrect the old discovery id on focus or failed logout',async()=>{active=true;sessionStorage.setItem('hiatlas.support-session.v1','support-a');const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/auth/logout')return Promise.resolve(response({},503));if(url==='/api/support-sessions/support-a'&&!active)return Promise.resolve(response({},403));return original(url,init);}));render(<App/>);await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});fireEvent.click(screen.getByRole('button',{name:'Encerrar sessão de suporte'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar encerramento'}));await screen.findByRole('heading',{name:'Suporte HiAtlas'});fireEvent.click(screen.getByRole('button',{name:'Sair'}));await screen.findByText(/Serviço temporariamente indisponível/);fireEvent(window,new Event('focus'));await waitFor(()=>expect(screen.getByRole('heading',{name:'Suporte HiAtlas'})).toBeVisible());expect(screen.queryByRole('region',{name:'Sessão de suporte somente leitura'})).not.toBeInTheDocument();});

it('end aborts a delayed derived workspace and its late response cannot refill normal portal',async()=>{const original=fetch;let finish:((value:Response)=>void)|undefined,signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.endsWith('/workspace')?new Promise<Response>(resolve=>{finish=resolve;signal=init?.signal??undefined;}):original(url,init)));await start();await waitFor(()=>expect(finish).toBeDefined());fireEvent.click(screen.getByRole('button',{name:'Encerrar sessão de suporte'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar encerramento'}));await screen.findByRole('heading',{name:'Suporte HiAtlas'});expect(signal?.aborted).toBe(true);finish!(response({effective_access:{read_only:true,capabilities:[]},modules:[{code:'PROCUREMENT',label:'Dados antigos exclusivos',contracted:true,active:true,enabled:true,operational_available:false}]}));await waitFor(()=>expect(screen.queryByText('Dados antigos exclusivos')).not.toBeInTheDocument());});
it('focus revalidation revocation aborts workspace and removes viewed identity and storage',async()=>{const original=fetch;let finish:((value:Response)=>void)|undefined,signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.endsWith('/workspace')?new Promise<Response>(resolve=>{finish=resolve;signal=init?.signal??undefined;}):original(url,init)));await start();await waitFor(()=>expect(finish).toBeDefined());supportStatus=403;fireEvent(window,new Event('focus'));await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(signal?.aborted).toBe(true);expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();finish!(response({effective_access:{read_only:true,capabilities:[]},modules:[]}));expect(screen.queryByText('Usuário visualizado: Ana cliente')).not.toBeInTheDocument();});
it('new HTTP session rejected on restore removes support reference and shows login',async()=>{active=true;supportStatus=401;sessionStorage.setItem('hiatlas.support-session.v1','support-a');render(<App/>);await screen.findByLabelText('E-mail');expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();expect(sessionStorage.getItem('hiatlas.access-context.v1')).toBeNull();expect(screen.queryByText('Ana cliente')).not.toBeInTheDocument();});
it('workspace permission rejection clears all derived contents into safe selection',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.endsWith('/workspace')?Promise.resolve(response({},403)):original(url,init)));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(screen.queryByRole('heading',{name:'Ambiente do usuário'})).not.toBeInTheDocument();expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();});
it('keyboard Escape cancels start and restores focus without creating support',async()=>{render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));const trigger=await screen.findByRole('button',{name:'Iniciar sessão de suporte'});trigger.focus();fireEvent.click(trigger);const dialog=screen.getByRole('dialog');fireEvent.keyDown(dialog,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(trigger).toHaveFocus();expect(calls.some(c=>c.path==='/support-sessions'&&c.init.method==='POST')).toBe(false);});
it('theme controls preserve the active banner and operator scope',async()=>{await start();fireEvent.click(screen.getByRole('button',{name:'Tema escuro'}));expect(screen.getByRole('main')).toHaveAttribute('data-theme','dark');expect(screen.getByRole('region',{name:'Sessão de suporte somente leitura'})).toHaveTextContent('Operador: Operador real');fireEvent.click(screen.getByRole('button',{name:'Tema claro'}));expect(screen.getByRole('main')).toHaveAttribute('data-theme','light');expect(screen.getByRole('timer',{name:'Tempo restante de suporte'})).toBeVisible();});
it('two independent flow clients keep distinct derived contexts and ending A never aborts B',async()=>{
 const {AuthContext}=await import('../auth/state');const {Context}=await import('../platform/state');const {ApiClient}=await import('../api/client');const {default:ContractShell}=await import('../platform/ContractShell');
 vi.stubGlobal('sessionStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
 let finishB:((value:Response)=>void)|undefined,signalB:AbortSignal|undefined,workspaceScopeB:string|null=null;
 const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{const scope=new Headers(init?.headers).get('X-HiAtlas-Context');if(url==='/api/support-sessions'&&init?.method==='POST')return Promise.resolve(response({...session,id:scope==='parent-b'?'support-b':'support-a',parent_context_id:scope,context_id:scope==='parent-b'?'child-b':'child-a',contract_id:scope==='parent-b'?'contract-b':'contract-a'},201));if(url==='/api/support-sessions/support-b/workspace'){workspaceScopeB=scope;signalB=init?.signal??undefined;return new Promise<Response>(resolve=>{finishB=resolve;});}if(url==='/api/support-sessions/support-a/end')return Promise.resolve(response(null,204));return original(url,init);}));
 function Flow({name}:{name:'a'|'b'}){const [api]=React.useState(()=>new ApiClient());api.setContext(`parent-${name}`);return <div data-testid={`flow-${name}`}><AuthContext.Provider value={{api,user:{user_id:'operator',display_name:'Operador real',platform_role:'PLATFORM_SUPPORT'},loading:false,busy:false,error:null,login:async()=>{},logout:async()=>{},retry:()=>{}}}><Context.Provider value={{selected:{id:`parent-${name}`,tenant_name:`Empresa ${name}`,contract_id:`contract-${name}`,contract_code:`CTR-${name}`,environment:'TEST',expires_at:'2099-01-01T00:00:00Z',capabilities:['memberships.read','support.session.start']},loading:false,busy:false,error:null,recovering:false,select:async()=>{},clear:async()=>{},retry:()=>{}}}><ContractShell/></Context.Provider></AuthContext.Provider></div>;}
 render(<><Flow name="a"/><Flow name="b"/></>);
 for(const name of ['a','b']){const flow=within(screen.getByTestId(`flow-${name}`));fireEvent.click(await flow.findByRole('button',{name:'Detalhes de Ana cliente'}));fireEvent.click(await flow.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(flow.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(flow.getByRole('button',{name:'Confirmar início somente leitura'}));await flow.findByRole('region',{name:'Sessão de suporte somente leitura'});}
 await waitFor(()=>expect(finishB).toBeDefined());const flowA=within(screen.getByTestId('flow-a'));fireEvent.click(flowA.getByRole('button',{name:'Encerrar sessão de suporte'}));fireEvent.click(flowA.getByRole('button',{name:'Confirmar encerramento'}));await flowA.findByRole('heading',{name:'Suporte HiAtlas'});expect(signalB?.aborted).toBe(false);finishB!(response({effective_access:{read_only:true,capabilities:[]},modules:[{code:'INVENTORY',label:'Estoque exclusivo B',contracted:true,active:true,enabled:true,operational_available:false}]}));expect(await within(screen.getByTestId('flow-b')).findByText('Estoque exclusivo B')).toBeVisible();expect(flowA.queryByText('Estoque exclusivo B')).not.toBeInTheDocument();expect(workspaceScopeB).toBe('child-b');
});



it('timer expiry discards the child and observes terminal state once without idle polling',async()=>{await start();const readsBefore=calls.filter(c=>c.path==='/support-sessions/support-a').length;vi.useFakeTimers();try{await act(async()=>{await vi.advanceTimersByTimeAsync(1000);});expect(calls.filter(c=>c.path==='/support-sessions/support-a')).toHaveLength(readsBefore);const expires=new Date(Date.now()+2500).toISOString();const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/support-sessions/support-a'?Promise.resolve(response({...session,expires_at:expires})):original(url,init)));await act(async()=>{fireEvent(window,new Event('focus'));await Promise.resolve();});await act(async()=>{await vi.advanceTimersByTimeAsync(0);});expect(screen.getByRole('timer')).toHaveTextContent('0:03');await act(async()=>{await vi.advanceTimersByTimeAsync(2501);});expect(screen.queryByRole('region',{name:'Sessão de suporte somente leitura'})).not.toBeInTheDocument();expect(screen.getByText(/Sessão de suporte encerrada, expirada ou indisponível/)).toHaveAttribute('role','status');expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();}finally{vi.restoreAllMocks();vi.useRealTimers();}});
it('newly discovered support immediately hides management while session validation is delayed',async()=>{render(<App/>);await screen.findByRole('button',{name:'Detalhes de Ana cliente'});active=true;const original=fetch;let finish:((value:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/support-sessions/support-a'?new Promise<Response>(resolve=>{finish=resolve;}):original(url,init)));fireEvent(window,new Event('focus'));await waitFor(()=>expect(finish).toBeDefined());expect(screen.queryByRole('button',{name:'Usuários'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Trocar empresa/contrato'})).not.toBeInTheDocument();finish!(response(session));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});});
it('successful support revalidation refreshes live workspace module metadata for the same session ids',async()=>{await start();expect(await screen.findByText('Módulo contratado · Ativo')).toBeVisible();const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.endsWith('/workspace')?Promise.resolve(response({effective_access:{read_only:true,capabilities:[]},modules:[{code:'PROCUREMENT',label:'Compras',contracted:true,active:false,enabled:false,operational_available:false}]})):original(url,init)));fireEvent(window,new Event('focus'));expect(await screen.findByText('Módulo contratado · Inativo')).toBeVisible();expect(screen.queryByText('Módulo contratado · Ativo')).not.toBeInTheDocument();});
it('shared parent and support expiry deadline retains neutral notice and observes support termination once',async()=>{active=true;sessionStorage.setItem('hiatlas.support-session.v1','support-a');vi.useFakeTimers();try{const deadline=Date.now()+2500;const expires=new Date(deadline).toISOString();const original=fetch;let observations=0;const callbacks:(()=>void)[]=[];const originalTimeout=window.setTimeout;vi.spyOn(window,'setTimeout').mockImplementation((handler,timeout,...args)=>{if(timeout===2500&&typeof handler==='function')callbacks.push(()=>handler(...args));return originalTimeout(handler,timeout,...args);});vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/context')return Promise.resolve(response({id:'parent-a',tenant_name:'Empresa A',contract_id:'contract-a',contract_code:'CTR-A',environment:'TEST',expires_at:expires,capabilities:['memberships.read','support.session.start','support.history.read'],support_session_id:'support-a'}));if(url==='/api/support-sessions/support-a'){if(Date.now()>=Date.parse(expires))observations++;return Promise.resolve(response({...session,expires_at:expires}));}return original(url,init);}));await act(async()=>{render(<App/>);await Promise.resolve();});expect(screen.getByRole('region',{name:'Sessão de suporte somente leitura'})).toBeVisible();expect(callbacks).toHaveLength(2);vi.setSystemTime(deadline);await act(async()=>{callbacks[0]();await Promise.resolve();});expect(screen.queryByRole('region',{name:'Sessão de suporte somente leitura'})).not.toBeInTheDocument();expect(screen.getByText(/Sessão de suporte encerrada, expirada ou indisponível/)).toHaveAttribute('role','status');expect(observations).toBe(1);expect(sessionStorage.getItem('hiatlas.support-session.v1')).toBeNull();}finally{vi.restoreAllMocks();vi.useRealTimers();}});


it('starting support focuses and announces the permanent mode while timer stays quiet',async()=>{await start();const banner=screen.getByRole('region',{name:'Sessão de suporte somente leitura'});expect(banner).toHaveFocus();expect(within(banner).getByRole('status')).toHaveTextContent('SESSÃO DE SUPORTE — SOMENTE LEITURA');expect(screen.getByRole('timer')).not.toHaveAttribute('aria-live','polite');});



it('parent-first context revocation retains support terminal notice and aborts delayed child validation',async()=>{await start();const original=fetch;let signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/context')return Promise.resolve(response({code:'CONTEXT_INVALID'},403));if(url==='/api/support-sessions/support-a'){signal=init?.signal??undefined;return new Promise<Response>(()=>{});}return original(url,init);}));fireEvent(window,new Event('focus'));await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(screen.getByText(/Sessão de suporte encerrada, expirada ou indisponível/)).toHaveAttribute('role','status');expect(signal?.aborted).toBe(true);expect(screen.queryByText('Usuário visualizado: Ana cliente')).not.toBeInTheDocument();});
it('memory-only start survives storage failure and parent timer first retains notice and terminal observation',async()=>{const deadline=Date.now()+30000;const expires=new Date(deadline).toISOString();const original=fetch;let parentExpiry:(()=>void)|undefined,observations=0;const originalTimeout=window.setTimeout;vi.spyOn(window,'setTimeout').mockImplementation((handler,timeout,...args)=>{if(!parentExpiry&&timeout&&timeout>29000&&timeout<31000&&typeof handler==='function')parentExpiry=()=>handler(...args);return originalTimeout(handler,timeout,...args);});vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url==='/api/context')return Promise.resolve(response({id:'parent-a',tenant_name:'Empresa A',contract_id:'contract-a',contract_code:'CTR-A',environment:'TEST',expires_at:expires,capabilities:['memberships.read','support.session.start','support.history.read'],support_session_id:null}));if(url==='/api/support-sessions'&&init?.method==='POST')return Promise.resolve(response({...session,expires_at:expires},201));if(url==='/api/support-sessions/support-a'){observations++;return Promise.resolve(response({},403));}return original(url,init);}));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Detalhes de Ana cliente'}));vi.stubGlobal('sessionStorage',{getItem:()=>{throw new Error('Storage unavailable');},setItem:()=>{throw new Error('Storage unavailable');},removeItem:()=>{throw new Error('Storage unavailable');}});fireEvent.click(await screen.findByRole('button',{name:'Iniciar sessão de suporte'}));fireEvent.change(screen.getByLabelText('Motivo do atendimento'),{target:{value:'Investigar chamado'}});fireEvent.click(screen.getByRole('button',{name:'Confirmar início somente leitura'}));await screen.findByRole('region',{name:'Sessão de suporte somente leitura'});expect(parentExpiry).toBeDefined();await act(async()=>{parentExpiry!();await Promise.resolve();});expect(screen.getByText(/Sessão de suporte encerrada, expirada ou indisponível/)).toHaveAttribute('role','status');expect(observations).toBe(1);expect(screen.queryByText('Usuário visualizado: Ana cliente')).not.toBeInTheDocument();});
it('failed end error is accessible within the active confirmation dialog',async()=>{await start();endStatus=503;fireEvent.click(screen.getByRole('button',{name:'Encerrar sessão de suporte'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Confirmar encerramento'}));expect(await within(screen.getByRole('dialog')).findByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível');});
it('ended history exposes the read-only mode and duration derived from server timestamps',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.startsWith('/api/support-sessions?')?Promise.resolve(response({items:[{...session,id:'history-ended',context_id:undefined,parent_context_id:undefined,status:'ENDED',started_at:'2026-10-02T12:00:00Z',ended_at:'2026-10-02T12:07:35Z'}],total:1,limit:20,offset:0})):original(url,init)));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Sessões de suporte'}));expect(await screen.findByText('Modo: Somente leitura')).toBeVisible();expect(screen.getByText('Duração: 7 min 35 s')).toBeVisible();expect(screen.queryByText('child-a')).not.toBeInTheDocument();expect(screen.queryByText('parent-a')).not.toBeInTheDocument();});
it('active history reports duration as in progress without inventing an end time',async()=>{const original=fetch;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.startsWith('/api/support-sessions?')?Promise.resolve(response({items:[{...session,context_id:undefined,parent_context_id:undefined}],total:1,limit:20,offset:0})):original(url,init)));render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Sessões de suporte'}));expect(await screen.findByText('Duração: Em andamento')).toBeVisible();expect(screen.getByText('Modo: Somente leitura')).toBeVisible();});
