// Real HTTPS/FastAPI/PostgreSQL/Chrome proof; synthetic fixtures only.
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.HIATLAS_PLAYWRIGHT_MODULE||'playwright');
const origin=process.env.PUBLIC_ORIGIN,password=process.env.HIATLAS_E2E_PASSWORD,state=process.env.HIATLAS_E2E_STATE;
assert.equal(origin,'https://localhost:5188');assert(state&&password,'Private synthetic environment required');
const output=path.resolve('../docs/superpowers/validation/hiatlas-datahub/visual');mkdirSync(output,{recursive:true});
function fixture(action,variant,source){const args=[path.resolve('../scripts/datahub_browser_fixture.py'),action];if(variant)args.push('--variant',variant);if(source)args.push('--source',source);try{return JSON.parse(execFileSync(path.resolve('../backend/.venv/Scripts/python.exe'),args,{encoding:'utf8',stdio:'pipe'}));}catch{throw new Error('Synthetic fixture failed; sensitive diagnostics redacted');}}
async function api(page,route,body,contextId,method){return page.evaluate(async({route,body,contextId,method})=>{const headers={};if(contextId)headers['X-HiAtlas-Context']=contextId;const verb=method??(body===undefined?'GET':'POST');if(body!==undefined)headers['Content-Type']='application/json';if(verb!=='GET'){const csrf=await fetch('/api/auth/csrf');if(!csrf.ok)return{status:csrf.status};headers['X-CSRF-Token']=(await csrf.json()).token;}const response=await fetch('/api'+route,{method:verb,headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:response.status,body:response.status===204?null:await response.json()};},{route,body,contextId,method});}
const browser=await chromium.launch({headless:true,channel:'chrome'});let stage='startup';const errors=[],confirmCommands=[];let active;
async function fresh(){const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});const page=await ctx.newPage();page.on('pageerror',()=>errors.push('pageerror'));page.on('request',r=>{if(/\/datahub\/imports\/[^/]+\/confirm$/.test(new URL(r.url()).pathname))confirmCommands.push(r.postDataJSON());});return[ctx,page];}
async function login(page,email){await page.goto(origin);await page.getByLabel('E-mail',{exact:true}).fill(email);await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar no HiAtlas',exact:true}).click();await page.getByRole('heading',{name:'Selecionar ambiente',exact:true}).waitFor();}
async function select(page,code){await page.getByRole('button',{name:'Acessar contrato '+code,exact:true}).click();await page.getByTestId('contract-context').getByText(code,{exact:true}).waitFor();return page.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1'));}
async function shot(page,name){await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});}
async function upload(page,file){await page.getByLabel('Planilha XLSX').setInputFiles(file);await page.getByRole('button',{name:'Validar e gerar preview',exact:true}).click();await page.getByRole('heading',{name:'Revisar importação',exact:true}).waitFor();await page.getByText('Processando solicitação…',{exact:true}).waitFor({state:'hidden'});}
function previewCard(page){return page.locator('.datahub-card').filter({has:page.getByRole('heading',{name:'Revisar importação',exact:true})});}
async function commit(page){await page.getByRole('button',{name:'Revisar e confirmar importação',exact:true}).click();await page.getByRole('dialog').getByText(/UNIT-SYN/).waitFor();await shot(page,'confirm-contextual');await page.getByRole('button',{name:'Confirmar importação',exact:true}).click();await page.getByText('Importação concluída.',{exact:true}).waitFor();}
try{
 stage='seed';fixture('clean');fixture('seed');
 const [adminCtx,admin]=await fresh();active=admin;await login(admin,'admin@example.test');let context=await select(admin,'CTR-A');await admin.getByRole('button',{name:'Data Hub > Excel',exact:true}).click();await admin.getByLabel('Modelo oficial').selectOption('COORDENACAO');await admin.getByText('Financeiro indisponível nesta V1.',{exact:true}).waitFor();
 stage='official template';const downloadPromise=admin.waitForEvent('download');await admin.getByRole('button',{name:'Baixar modelo oficial',exact:true}).click();const download=await downloadPromise;const source=path.join(state,'official.xlsx');await download.saveAs(source);const valid=fixture('fill','valid',source),invalid=fixture('fill','invalid',source),changed=fixture('fill','changed',source);
 stage='five datasets preview/commit';await upload(admin,valid);await previewCard(admin).getByText('Modelo identificado: Coordenação · v1',{exact:true}).waitFor();await previewCard(admin).locator('p').filter({hasText:/5 linha/}).waitFor();assert.equal(fixture('inspect').records,0);await shot(admin,'desktop-light-preview');await commit(admin);assert.equal(fixture('inspect').records,5);assert.equal(fixture('inspect').committed_events,1);assert.equal(await admin.evaluate(()=>document.activeElement?.id),'preview-heading');
 stage='history/export';const history=await api(admin,'/datahub/imports',undefined,context);const committed=history.body.items[0];assert.equal(committed.status,'COMMITTED');assert.equal((await api(admin,`/datahub/imports/${committed.id}/confirm`,confirmCommands[0],context)).status,200);assert.equal(fixture('inspect').committed_events,1);const key=crypto.randomUUID();assert.equal((await api(admin,`/datahub/imports/${committed.id}/confirm`,{expected_version:3,idempotency_key:key},context)).status,409);await admin.getByRole('button',{name:'Exportar dados',exact:true}).click();const exportedPromise=admin.waitForEvent('download');await admin.getByRole('button',{name:'Confirmar exportação',exact:true}).click();const exported=await exportedPromise;await exported.saveAs(path.join(state,'export.xlsx'));
 stage='duplicate identical';await upload(admin,valid);await previewCard(admin).locator('p').filter({hasText:/5 ignorada/}).waitFor();await commit(admin);assert.equal(fixture('inspect').records,5);assert.equal(fixture('inspect').committed_events,2);
 stage='changed duplicate';await upload(admin,changed);await previewCard(admin).getByText('Dados rejeitados',{exact:true}).waitFor();assert.equal(await admin.getByRole('button',{name:'Revisar e confirmar importação',exact:true}).count(),0);
 stage='formula rejected';await upload(admin,invalid);await previewCard(admin).getByText('Dados rejeitados',{exact:true}).waitFor();await shot(admin,'invalid-formula');
 stage='dark/mobile/keyboard';await admin.getByRole('button',{name:'Tema escuro',exact:true}).click();await shot(admin,'desktop-dark');await admin.setViewportSize({width:390,height:844});await shot(admin,'mobile-dark');assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await admin.getByRole('button',{name:'Tema claro',exact:true}).click();await shot(admin,'mobile-light');await admin.keyboard.press('Tab');assert.notEqual(await admin.evaluate(()=>document.activeElement?.tagName),'BODY');await admin.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));assert(await admin.getByTestId('contract-context').isVisible());await admin.setViewportSize({width:1440,height:1000});await admin.reload();await admin.getByTestId('contract-context').waitFor();await admin.getByRole('button',{name:'Data Hub > Excel',exact:true}).click();await admin.getByRole('heading',{name:'Histórico de importações'}).waitFor();
 stage='member normal context and two tabs';const [memberCtx,member]=await fresh();await login(member,'member@example.test');const memberContext=await select(member,'CTR-A');await member.getByLabel('Modelo oficial').waitFor();const tab=await memberCtx.newPage();await tab.goto(origin);await tab.getByRole('heading',{name:'Selecionar ambiente'}).waitFor();await select(tab,'CTR-A2');assert.equal((await api(tab,'/datahub/imports/'+committed.id,undefined,await tab.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1')))).status,404);assert.equal(await member.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1')),memberContext);
 stage='foreign valid IDs A2/B';await admin.getByRole('button',{name:'Trocar empresa/contrato',exact:true}).click();context=await select(admin,'CTR-A2');assert.equal((await api(admin,'/datahub/imports/'+committed.id,undefined,context)).status,404);await admin.getByRole('button',{name:'Trocar empresa/contrato',exact:true}).click();context=await select(admin,'CTR-B');assert.equal((await api(admin,'/datahub/imports/'+committed.id+'/rows',undefined,context)).status,404);
 stage='support manual denied';const [supportCtx,support]=await fresh();await login(support,'support@example.test');const supportContext=await select(support,'CTR-A');assert.equal(await support.getByRole('button',{name:'Data Hub > Excel',exact:true}).count(),0);assert.equal((await api(support,'/datahub/templates',undefined,supportContext)).status,403);await shot(support,'support-denied');
 stage='permission revoked between preview and confirm';await upload(member,valid);fixture('revoke','permission');await member.getByRole('button',{name:'Revisar e confirmar importação',exact:true}).click();await member.getByRole('button',{name:'Confirmar importação',exact:true}).click();await member.getByRole('alert').waitFor();assert.equal(fixture('inspect').records,5);await shot(member,'permission-revoked');
 stage='module revoked';fixture('revoke','module');assert.equal((await api(member,'/datahub/templates',undefined,memberContext)).status,403);
 stage='storage/logout';const stored=await member.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)}));assert.deepEqual(stored.local,['hiatlas-theme']);assert.deepEqual(stored.session,['hiatlas.access-context.v1']);await member.getByRole('button',{name:'Sair',exact:true}).click();await member.getByLabel('E-mail',{exact:true}).waitFor();assert.equal(await member.evaluate(()=>sessionStorage.length),0);
 await adminCtx.close();await memberCtx.close();await supportCtx.close();assert.equal(errors.length,0);console.log('[PASS] DataHub Admin/member/Support real HTTPS/Chrome:five datasets, preview/commit/audit, duplicate/formula/export, A/A2/B, revocations, reload/two tabs, light/dark/mobile/keyboard/storage/logout');
}catch(error){writeFileSync(path.join(state,'failure.txt'),String(error?.message||error));if(active)await active.screenshot({path:path.join(state,'failure.png')}).catch(()=>{});console.error('[FAIL] DataHub E2E stage='+stage+'; '+(error?.name||'Error')+'; sensitive diagnostics redacted');process.exitCode=1;}finally{await browser.close();}
