// Real Phase6 browser flows. No HTTP mocks, no real SMTP, no secret diagnostics.
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.HIATLAS_PLAYWRIGHT_MODULE || 'playwright');
const origin=process.env.HIATLAS_E2E_ORIGIN;
const password=process.env.HIATLAS_E2E_PASSWORD;
assert(origin && password,'Controlled E2E environment required');
const output=path.resolve('../docs/superpowers/validation/hiatlas-platform/phase-06-visual');
mkdirSync(output,{recursive:true});
let stage='startup';
const errors=[];
const unsafe=[];
const requests=[];
const browser=await chromium.launch({headless:true,channel:'chrome'});
async function fresh(){
 const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});
 const p=await ctx.newPage();p.on('pageerror',()=>errors.push('pageerror'));
 p.on('request',r=>{const u=new URL(r.url());if(u.origin!==origin||u.searchParams.has('token'))unsafe.push('unsafe request');if(/^\/api\/(memberships|roles|audit|capabilities)/.test(u.pathname))requests.push({path:u.pathname,context:r.headers()['x-hiatlas-context']});});
 return [ctx,p];
}
function fixture(action,recipient){
 const args=[path.resolve('../scripts/phase06_browser_fixture.py'),action];if(recipient)args.push('--recipient',recipient);
 try{return execFileSync(path.resolve('../backend/.venv/Scripts/python.exe'),args,{cwd:path.resolve('..'),stdio:'pipe',encoding:'utf8'}).trim();}catch{throw new Error('Controlled fixture failed; diagnostics suppressed');}
}
function deliveryLink(recipient){const message=JSON.parse(fixture('deliver',recipient));const link=message.text.split(/\s+/).find(word=>word.startsWith(origin+'/'));assert(link,'Fake transport link unavailable');return link;}
async function api(p,route,body,contextId,method){return p.evaluate(async ({route,body,contextId,method})=>{
 const headers={Accept:'application/json'};if(contextId)headers['X-HiAtlas-Context']=contextId;
 if(body!==undefined){headers['Content-Type']='application/json';const csrf=await(await fetch('/api/auth/csrf')).json();headers['X-CSRF-Token']=csrf.token;}
 const r=await fetch('/api'+route,{method:method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:JSON.stringify(body)});
 return {status:r.status,body:r.status===204?null:await r.json()};
},{route,body,contextId,method});}
async function shot(p,name){await p.locator('img').evaluateAll(images=>Promise.all(images.map(img=>img.decode().catch(()=>{}))));await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
async function login(p,email){await p.goto(origin);await p.getByLabel('E-mail',{exact:true}).fill(email);await p.getByLabel('Senha',{exact:true}).fill(password);await p.getByRole('button',{name:'Entrar no HiAtlas',exact:true}).click();await p.getByRole('heading',{name:'Selecionar ambiente',exact:true}).waitFor();}
async function select(p,code){await p.getByRole('button',{name:'Acessar contrato '+code,exact:true}).click();await p.getByTestId('contract-context').waitFor();assert(await p.getByTestId('contract-context').getByText(code,{exact:true}).isVisible());}
async function memberSearch(p,email){await p.getByLabel('Nome ou e-mail',{exact:true}).fill(email);await p.getByRole('button',{name:'Pesquisar usuários',exact:true}).click();}
async function details(p,name){await p.getByRole('button',{name:'Detalhes de '+name,exact:true}).click();await p.getByRole('button',{name:'Bloquear acesso',exact:true}).waitFor();}
async function confirm(p){await p.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});}
async function createUser(p,name,email){await p.getByRole('button',{name:'Novo usuário',exact:true}).click();const d=p.getByRole('dialog');await d.getByLabel('Nome',{exact:true}).fill(name);await d.getByLabel('E-mail',{exact:true}).fill(email);await d.getByLabel('Perfil',{exact:true}).selectOption({label:'Comprador Nacional'});await d.getByRole('button',{name:'Revisar solicitação',exact:true}).click();await confirm(p);}
async function backUsers(p){await p.getByRole('button',{name:'Usuários',exact:true}).click();}
async function noStorageData(p){const state=await p.evaluate(()=>({local:JSON.stringify(localStorage),session:JSON.stringify(sessionStorage)}));for(const forbidden of ['@example.test','permissions','before','after','capabilities','Comprador','member_user']){assert(!state.local.includes(forbidden)&&!state.session.includes(forbidden),'Business data persisted');}}
try{
 const ids=JSON.parse(fixture('seed'));
 const [adminContext,admin]=await fresh();stage='admin login and context';await login(admin,'admin@example.test');await select(admin,'CTR-A');
 await admin.getByRole('button',{name:'Novo usuário',exact:true}).waitFor();await shot(admin,'admin-users-light');await admin.getByRole('button',{name:'Próxima página',exact:true}).click();await admin.getByText('21–23 de 23 usuários',{exact:true}).waitFor();await admin.getByRole('button',{name:'Página anterior',exact:true}).click();await admin.getByRole('button',{name:'Novo usuário',exact:true}).focus();await admin.keyboard.press('Enter');await admin.getByRole('dialog').waitFor();await admin.keyboard.press('Tab');assert(await admin.getByRole('dialog').getByLabel('E-mail',{exact:true}).evaluate(el=>el===document.activeElement));await admin.keyboard.press('Escape');await admin.getByRole('dialog').waitFor({state:'hidden'});assert(await admin.getByRole('button',{name:'Novo usuário',exact:true}).evaluate(el=>el===document.activeElement));
 const contextId=await admin.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1'));assert(contextId);
 stage='admin create pending invitation';await createUser(admin,'Convidado Fase 6','phase6-invited@example.test');await memberSearch(admin,'phase6-invited@example.test');await details(admin,'Convidado Fase 6');
 await shot(admin,'admin-pending-invite');const pending=await api(admin,'/memberships?search=phase6-invited',undefined,contextId);assert.equal(pending.status,200);assert.equal(pending.body.items.length,1);assert.equal(pending.body.items[0].invitation_pending,true);const memberId=pending.body.items[0].id;
 stage='real invitation acceptance';const link=deliveryLink('phase6-invited@example.test');const token=new URLSearchParams(new URL(link).hash.slice(1)).get('token');const [recipientContext,recipient]=await fresh();await recipient.goto(link);await recipient.getByLabel('Nova senha',{exact:true}).fill(password);await recipient.getByLabel('Confirmar nova senha',{exact:true}).fill(password);await recipient.getByRole('button',{name:'Aceitar convite',exact:true}).click();await recipient.getByText('Convite aceito.',{exact:true}).waitFor();assert(!recipient.url().includes(token));await shot(recipient,'invite-accepted');
 stage='admin role assignment and status';await backUsers(admin);await memberSearch(admin,'phase6-invited@example.test');await details(admin,'Convidado Fase 6');await admin.getByRole('button',{name:'Alterar perfil',exact:true}).click();await admin.getByRole('dialog').getByLabel('Novo perfil',{exact:true}).selectOption({label:'Coordenação'});await confirm(admin);await admin.getByText('Perfil: Coordenação',{exact:true}).waitFor();
 await admin.getByRole('button',{name:'Bloquear acesso',exact:true}).click();assert(await admin.getByRole('dialog').getByText(/CTR-A/).count()>0);await shot(admin,'admin-block-confirmation');await confirm(admin);await admin.getByRole('button',{name:'Desbloquear acesso',exact:true}).click();await confirm(admin);
 const changed=await api(admin,'/memberships/'+memberId,undefined,contextId);assert.equal(changed.status,200);assert.equal(changed.body.blocked,false);assert.equal(changed.body.active,true);assert.equal(changed.body.invitation_pending,false);assert.equal(changed.body.role_id,ids.role_opt_out);
 stage='admin role creation and support flag';await admin.getByRole('button',{name:/^Perfis/}).click();await admin.getByRole('button',{name:'Criar perfil',exact:true}).click();const roleDialog=admin.getByRole('dialog');await roleDialog.getByLabel('Código',{exact:true}).fill('E2E_PHASE6');await roleDialog.getByLabel('Nome do perfil',{exact:true}).fill('Perfil E2E');await roleDialog.getByLabel('Descrição',{exact:true}).fill('Perfil exclusivo de testes descartáveis');await roleDialog.getByRole('button',{name:'Revisar perfil',exact:true}).click();await confirm(admin);await admin.getByRole('button',{name:'Editar perfil Perfil E2E',exact:true}).click();const currentRoles=await api(admin,'/roles?limit=100',undefined,contextId);const editing=currentRoles.body.items.find(item=>item.code==='E2E_PHASE6');assert.equal((await api(admin,'/roles/'+editing.id,{expected_version:editing.version,description:'Alteração concorrente controlada'},contextId,'PATCH')).status,200);await admin.getByRole('dialog').getByRole('button',{name:'Revisar perfil',exact:true}).click();await admin.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await admin.getByRole('dialog').getByRole('alert').waitFor();await shot(admin,'admin-version-conflict');await admin.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();await admin.getByRole('button',{name:'Editar perfil Perfil E2E',exact:true}).click();await admin.getByRole('dialog').getByLabel('Atribuível pelo suporte',{exact:true}).check();await admin.getByRole('dialog').getByRole('button',{name:'Revisar perfil',exact:true}).click();await confirm(admin);await shot(admin,'admin-roles-light');await admin.getByRole('button',{name:'Editar perfil Financeiro',exact:true}).click();await admin.getByRole('dialog').getByLabel('Atribuível pelo suporte',{exact:true}).uncheck();await admin.getByRole('dialog').getByLabel('Descrição',{exact:true}).fill('Sensibilidade histórica preservada');await admin.getByRole('dialog').getByRole('button',{name:'Revisar perfil',exact:true}).click();await confirm(admin);const financeRoles=await api(admin,'/roles?limit=100',undefined,contextId);const financeRole=financeRoles.body.items.find(item=>item.id===ids.role_finance);assert.equal(financeRole.support_assignable,false);assert.equal(financeRole.support_eligible,false);assert.equal(financeRole.sensitivity_locked,true);
 stage='admin contextual audit';await admin.getByRole('button',{name:'Auditoria',exact:true}).click();await admin.getByRole('heading',{name:'Auditoria',exact:true}).waitFor();const audited=await api(admin,'/audit?limit=100',undefined,contextId);assert.equal(audited.status,200);assert(audited.body.items.some(row=>row.action==='membership.status.changed'));assert(audited.body.items.some(row=>row.action==='membership.role.assigned'));await shot(admin,'admin-audit-light');await admin.getByRole('button',{name:'Tema escuro'}).click();await shot(admin,'admin-audit-dark');
 stage='support contextual user management';const [supportContext,support]=await fresh();await login(support,'support@example.test');await select(support,'CTR-A');await support.getByRole('button',{name:'Novo usuário',exact:true}).waitFor();assert.equal(await support.getByRole('button',{name:'Auditoria',exact:true}).count(),0);assert.equal(await support.getByRole('button',{name:/^Perfis/}).count(),0);const supportId=await support.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1'));await createUser(support,'Pendente Suporte','phase6-support@example.test');await memberSearch(support,'phase6-support@example.test');await details(support,'Pendente Suporte');await support.getByRole('button',{name:'Reemitir convite',exact:true}).click();await confirm(support);
 stage='support reset and assign only eligible role';await backUsers(support);await memberSearch(support,'member@example.test');await details(support,'Usuário existente');await support.getByRole('button',{name:'Enviar link de redefinição',exact:true}).click();await confirm(support);await support.getByRole('button',{name:'Alterar perfil',exact:true}).click();assert.equal(await support.getByRole('option',{name:'Financeiro',exact:true}).count(),0);assert.equal(await support.getByRole('option',{name:'Diretoria',exact:true}).count(),0);await support.getByRole('dialog').getByLabel('Novo perfil',{exact:true}).selectOption({label:'Coordenação'});await confirm(support);
 const member=await api(support,'/memberships/'+ids.member_a,undefined,supportId);assert.equal(member.status,200);const denied=await api(support,'/memberships/'+ids.member_a+'/role',{role_id:ids.role_finance,expected_version:member.body.version},supportId,'PUT');assert.equal(denied.status,403);const rolesDenied=await api(support,'/roles',{code:'FORBIDDEN_E2E',name:'Forbidden'},supportId);assert.equal(rolesDenied.status,403);
 stage='support sanitized audit and mobile';await support.getByRole('button',{name:'Histórico',exact:true}).click();await support.getByRole('heading',{name:/Histórico/}).waitFor();const history=await api(support,'/audit?limit=100',undefined,supportId);assert.equal(history.status,200);for(const row of history.body.items){for(const forbidden of ['before','after','reason','ciphertext'])assert(!(forbidden in row));}await shot(support,'support-history-light');await support.getByRole('button',{name:'Tema escuro'}).click();await shot(support,'support-history-dark');await support.setViewportSize({width:390,height:844});assert(await support.locator('.table-scroll table').evaluate(el=>el.getBoundingClientRect().width>=900),'Mobile audit columns must remain readable');const mobileEvents=support.getByRole('region',{name:'Tabela de eventos do contrato'});await mobileEvents.focus();await support.keyboard.press('ArrowRight');await support.waitForFunction(()=>document.querySelector('.table-scroll').scrollLeft>0);await mobileEvents.evaluate(el=>el.scrollLeft=0);await shot(support,'support-mobile');assert(await support.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await support.getByRole('button',{name:'Usuários',exact:true}).focus();assert(await support.getByRole('button',{name:'Usuários',exact:true}).evaluate(el=>el===document.activeElement));await support.keyboard.press('Enter');await support.getByLabel('Nome ou e-mail',{exact:true}).waitFor();await support.getByRole('button',{name:'Detalhes de Usuário existente',exact:true}).waitFor();assert(await support.locator('.table-scroll table').evaluate(el=>el.getBoundingClientRect().width>=700),'Mobile membership columns must remain readable');await shot(support,'support-users-mobile');
 stage='contract isolation A/A2/B';for(const code of ['CTR-A2','CTR-B']){await admin.getByRole('button',{name:'Trocar empresa/contrato',exact:true}).click();await admin.getByRole('button',{name:'Acessar contrato '+code,exact:true}).waitFor();await select(admin,code);await memberSearch(admin,'phase6-invited@example.test');const isolatedId=await admin.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1'));const absent=await api(admin,'/memberships?search=phase6-invited',undefined,isolatedId);assert.equal(absent.status,200);assert.equal(absent.body.items.length,0);assert.equal((await api(admin,'/memberships/'+memberId,undefined,isolatedId)).status,404);const scopedAudit=await api(admin,'/audit?limit=100',undefined,isolatedId);assert.equal(scopedAudit.status,200);assert(!scopedAudit.body.items.some(row=>row.entity_id===memberId));assert.equal((await api(admin,'/audit/'+audited.body.items[0].id,undefined,isolatedId)).status,404);const localMemberId=code==='CTR-A2'?ids.member_a2:ids.member_b;const localMember=await api(admin,'/memberships/'+localMemberId,undefined,isolatedId);assert.equal(localMember.status,200);assert.equal((await api(admin,'/memberships/'+localMemberId+'/role',{role_id:ids.role_basic,expected_version:localMember.body.version},isolatedId,'PUT')).status,404);}
 stage='storage and request scope';await noStorageData(admin);await noStorageData(support);assert(requests.length>0);assert(requests.every(r=>r.context),'Unscoped management request');assert.deepEqual(errors,[]);assert.deepEqual(unsafe,[]);await adminContext.close();await recipientContext.close();await supportContext.close();
 console.log('PASS Phase6: Admin login/context/users/invite/real acceptance/role/block/unblock/profile create+edit/audit; Support create/resend/reset/eligible role/manual sensitive denial/sanitized history; A/A2/B isolation; light/dark; desktop/mobile; keyboard; no business storage; contextual headers; fake email only.');
}catch{
 const failed=browser.contexts().at(-1)?.pages().at(-1);if(failed)await failed.screenshot({path:path.join(process.env.HIATLAS_E2E_STATE,'phase06-failure.png'),fullPage:true}).catch(()=>{});
 console.error('FAIL Phase6 E2E at '+stage+' (sensitive diagnostics suppressed)');process.exitCode=1;
}finally{await browser.close();}
