// Real Phase7 browser flows; no HTTP mocks, external SMTP or secret diagnostics.
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.HIATLAS_PLAYWRIGHT_MODULE||'playwright');
const origin=process.env.HIATLAS_E2E_ORIGIN,password=process.env.HIATLAS_E2E_PASSWORD;
assert(origin&&password,'Controlled environment required');
const output=path.resolve('../docs/superpowers/validation/hiatlas-platform/phase-07-visual');
mkdirSync(output,{recursive:true});
let stage='startup';
const errors=[],unsafe=[],requests=[];
const browser=await chromium.launch({headless:true,channel:'chrome'});
function fixture(action){try{return execFileSync(path.resolve('../backend/.venv/Scripts/python.exe'),[path.resolve('../scripts/phase07_browser_fixture.py'),action],{cwd:path.resolve('..'),stdio:'pipe',encoding:'utf8'}).trim();}catch{throw new Error('Controlled fixture failed; diagnostics suppressed');}}
async function fresh(){const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000}});const page=await ctx.newPage();page.on('pageerror',()=>errors.push('pageerror'));page.on('request',r=>{const u=new URL(r.url());if(u.origin!==origin||u.searchParams.has('token'))unsafe.push('unsafe request');if(/^\/api\/(organization|contract\/modules)/.test(u.pathname))requests.push({path:u.pathname,context:r.headers()['x-hiatlas-context']});});return[ctx,page];}
async function api(page,route,body,contextId,method){return page.evaluate(async({route,body,contextId,method})=>{const headers={Accept:'application/json'};if(contextId)headers['X-HiAtlas-Context']=contextId;if(body!==undefined){headers['Content-Type']='application/json';const csrf=await(await fetch('/api/auth/csrf')).json();headers['X-CSRF-Token']=csrf.token;}const r=await fetch('/api'+route,{method:method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,body:r.status===204?null:await r.json()};},{route,body,contextId,method});}
async function login(page,email){await page.goto(origin);await page.getByLabel('E-mail',{exact:true}).fill(email);await page.getByLabel('Senha',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar no HiAtlas',exact:true}).click();await page.getByRole('heading',{name:'Selecionar ambiente',exact:true}).waitFor();}
async function select(page,code){await page.getByRole('button',{name:'Acessar contrato '+code,exact:true}).click();await page.getByTestId('contract-context').getByText(code,{exact:true}).waitFor();return page.evaluate(()=>sessionStorage.getItem('hiatlas.access-context.v1'));}
async function contextId(page){const context=await page.evaluate(()=>Object.values(sessionStorage));assert.equal(context.length,1);return context[0];}
async function shot(page,name){await page.locator('img').evaluateAll(images=>Promise.all(images.map(image=>image.decode().catch(()=>{}))));await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
async function confirm(page){await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});}
async function nodes(page,context,search=''){const result=await api(page,'/organization/nodes?limit=100&search='+encodeURIComponent(search),undefined,context);assert.equal(result.status,200);return result.body.items;}
async function createNode(page,context,kind,name,code,parent=null){await page.getByRole('button',{name:'Nova unidade',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Tipo de unidade',{exact:true}).selectOption(kind);assert.equal(await dialog.getByRole('option',{name:/PROJECT|Obra comercial/}).count(),0);await dialog.getByLabel('Nome da unidade',{exact:true}).fill(name);await dialog.getByLabel('Código',{exact:true}).fill(code);if(parent)await dialog.getByLabel('Unidade pai',{exact:true}).selectOption(parent);await dialog.getByRole('button',{name:'Revisar unidade',exact:true}).click();await confirm(page);const result=await nodes(page,context,code);const node=result.find(n=>n.code===code);assert(node);return node;}
async function modules(page,context){const result=await api(page,'/contract/modules',undefined,context);assert.equal(result.status,200);return result.body.items;}
async function configure(page,module,contracted,active){await page.getByRole('button',{name:'Configurar '+module.label,exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Módulo contratado',{exact:true}).setChecked(contracted);await dialog.getByLabel('Módulo ativo',{exact:true}).setChecked(active);await dialog.getByRole('button',{name:'Revisar módulo',exact:true}).click();await confirm(page);}
try{
 JSON.parse(fixture('seed'));
 const[adminCtx,admin]=await fresh();
 stage='admin login and context';await login(admin,'admin@example.test');await select(admin,'CTR-A');const aContext=await contextId(admin);
 stage='structure catalogue and keyboard';await admin.getByRole('button',{name:'Estrutura',exact:true}).click();await admin.getByRole('button',{name:'Nova unidade',exact:true}).click({trial:true});await admin.getByRole('button',{name:'Nova unidade',exact:true}).focus();await admin.keyboard.press('Enter');await admin.getByRole('dialog').getByLabel('Nome da unidade',{exact:true}).focus();await admin.keyboard.press('Tab');assert(await admin.getByRole('dialog').getByLabel('Código',{exact:true}).evaluate(el=>el===document.activeElement));await admin.keyboard.press('Escape');assert(await admin.getByRole('button',{name:'Nova unidade',exact:true}).evaluate(el=>el===document.activeElement));
 stage='admin physical hierarchy';const company=await createNode(admin,aContext,'COMPANY','Empresa Aurora','EMP-A');const branch=await createNode(admin,aContext,'BRANCH','Filial Curitiba','FIL-A',company.id);const dc=await createNode(admin,aContext,'DISTRIBUTION_CENTER','CD Curitiba','CD-A',company.id);await createNode(admin,aContext,'STORE','Loja Bauru','LOJA-A',branch.id);let worksite=await createNode(admin,aContext,'WORKSITE','Canteiro Norte','WS-A',branch.id);assert.equal(worksite.kind,'WORKSITE');assert.equal(worksite.parent_id,branch.id);await shot(admin,'admin-structure-light');
 stage='node edit and lifecycle';await admin.getByRole('button',{name:'Detalhes de Canteiro Norte',exact:true}).click();await admin.getByRole('button',{name:'Editar unidade',exact:true}).click();await admin.getByRole('dialog').getByLabel('Nome da unidade',{exact:true}).fill('Canteiro Norte revisado');await admin.getByRole('dialog').getByRole('button',{name:'Revisar unidade',exact:true}).click();await confirm(admin);worksite=(await nodes(admin,aContext,'WS-A'))[0];assert.equal(worksite.name,'Canteiro Norte revisado');await admin.getByRole('button',{name:'Inativar unidade',exact:true}).click();await admin.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click({trial:true});await shot(admin,'admin-inactivation-confirmation');await confirm(admin);worksite=(await nodes(admin,aContext,'WS-A'))[0];assert.equal(worksite.active,false);assert.equal(worksite.code,'WS-A');
 stage='real cyclic reparent attempt';const u1=await api(admin,'/organization/nodes',{kind:'UNIT',name:'Unidade ciclo um',code:'U-CYCLE-1',parent_id:company.id,active:true},aContext);const u2=await api(admin,'/organization/nodes',{kind:'UNIT',name:'Unidade ciclo dois',code:'U-CYCLE-2',parent_id:company.id,active:true},aContext);assert.equal(u1.status,201);assert.equal(u2.status,201);assert.equal((await api(admin,'/organization/nodes/'+u1.body.id,{parent_id:u2.body.id,expected_version:u1.body.version},aContext,'PATCH')).status,200);assert.equal((await api(admin,'/organization/nodes/'+u2.body.id,{parent_id:u1.body.id,expected_version:u2.body.version},aContext,'PATCH')).status,409);assert.equal((await api(admin,'/organization/nodes',{kind:'PROJECT',name:'Obra recusada',code:'PROJECT-INVALID',parent_id:company.id},aContext)).status,422);assert.equal((await api(admin,'/organization/nodes/'+branch.id,{active:false,expected_version:branch.version},aContext,'PATCH')).status,409);
 stage='module configure and availability';await admin.getByRole('button',{name:'Módulos',exact:true}).click();let procurement=(await modules(admin,aContext)).find(m=>m.code==='PROCUREMENT');assert(procurement&&!procurement.contracted);await configure(admin,procurement,true,true);procurement=(await modules(admin,aContext)).find(m=>m.code==='PROCUREMENT');assert(procurement.contracted&&procurement.active&&procurement.enabled);assert.equal(procurement.operational_available,false);await shot(admin,'admin-modules-light');
 stage='module optimistic conflict';await admin.getByRole('button',{name:'Configurar '+procurement.label,exact:true}).click();const moduleDialog=admin.getByRole('dialog');await moduleDialog.getByLabel('Módulo ativo',{exact:true}).setChecked(false);const concurrent=await api(admin,'/contract/modules/PROCUREMENT',{module_id:procurement.id,contracted:true,active:false,expected_version:procurement.version},aContext,'PATCH');assert.equal(concurrent.status,200);await moduleDialog.getByRole('button',{name:'Revisar módulo',exact:true}).click();await moduleDialog.getByRole('button',{name:'Confirmar',exact:true}).click();await moduleDialog.getByRole('alert').getByText('Os dados foram alterados. Atualize a página e tente novamente.',{exact:true}).waitFor();await shot(admin,'admin-module-conflict');await admin.keyboard.press('Escape');procurement=(await modules(admin,aContext)).find(m=>m.code==='PROCUREMENT');assert(procurement.contracted&&!procurement.active&&!procurement.enabled);
 stage='admin audit and themes';await admin.getByRole('button',{name:'Auditoria',exact:true}).click();const audit=await api(admin,'/audit?limit=100',undefined,aContext);assert.equal(audit.status,200);assert(audit.body.items.some(r=>r.entity_type==='organization_node'));assert(audit.body.items.some(r=>r.entity_type==='contract_module'));await admin.getByLabel('Ação',{exact:true}).fill('organization.node.created');await admin.getByRole('button',{name:'Filtrar histórico',exact:true}).click();await admin.waitForFunction(()=>{const text=document.querySelector('table')?.textContent||'';return text.includes('organization.node.created')&&!text.includes('context.selected');});await shot(admin,'admin-audit-light');await admin.getByRole('button',{name:'Tema escuro'}).click();await shot(admin,'admin-audit-dark');await admin.getByRole('button',{name:'Estrutura',exact:true}).click();await admin.getByRole('button',{name:'Detalhes de Empresa Aurora',exact:true}).waitFor();await shot(admin,'admin-structure-dark');await admin.setViewportSize({width:390,height:844});assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(admin,'admin-structure-mobile');await admin.getByRole('button',{name:'Módulos',exact:true}).click();await admin.getByRole('button',{name:'Configurar '+procurement.label,exact:true}).waitFor();await shot(admin,'admin-modules-mobile');assert(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await admin.setViewportSize({width:1440,height:1000});
 stage='support read-only metadata and direct denial';const[supportCtx,support]=await fresh();await login(support,'support@example.test');await select(support,'CTR-A');const supportId=await contextId(support);assert.equal(await support.getByRole('button',{name:'Estrutura',exact:true}).count(),0);await support.getByRole('button',{name:'Módulos',exact:true}).click();await support.getByText(procurement.label,{exact:true}).waitFor();assert.equal(await support.getByRole('button',{name:/Configurar /}).count(),0);assert.equal((await api(support,'/contract/modules/PROCUREMENT',{module_id:procurement.id,contracted:true,active:true,expected_version:procurement.version},supportId,'PATCH')).status,403);assert.equal((await api(support,'/organization/nodes',{kind:'WORKSITE',name:'Canteiro negado',code:'SUPPORT-DENIED',parent_id:null},supportId)).status,403);assert.equal((await api(support,'/organization/nodes?limit=20',undefined,supportId)).status,403);await shot(support,'support-modules-light');await support.getByRole('button',{name:'Tema escuro'}).click();await shot(support,'support-modules-dark');await support.setViewportSize({width:390,height:844});assert(await support.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot(support,'support-modules-mobile');
 stage='A A2 B organization module and audit isolation';for(const code of ['CTR-A2','CTR-B']){await admin.getByRole('button',{name:'Trocar empresa/contrato',exact:true}).click();await select(admin,code);const otherContext=await contextId(admin);await admin.getByRole('button',{name:'Estrutura',exact:true}).click();const rows=await nodes(admin,otherContext,'EMP-A');assert.equal(rows.length,0);assert.equal((await api(admin,'/organization/nodes/'+company.id,undefined,otherContext)).status,404);assert.equal((await api(admin,'/organization/nodes/'+dc.id,{name:'Cross contract',expected_version:dc.version},otherContext,'PATCH')).status,404);assert.equal((await api(admin,'/organization/nodes',{kind:'STORE',name:'Cross parent',code:'CROSS-PARENT',parent_id:branch.id},otherContext)).status,404);const otherModules=await modules(admin,otherContext);assert.equal(otherModules.find(m=>m.code==='PROCUREMENT').contracted,false);assert.equal((await api(admin,'/contract/modules/PROCUREMENT',{module_id:procurement.id,contracted:true,active:true,expected_version:procurement.version},otherContext,'PATCH')).status,404);const otherAudit=await api(admin,'/audit?limit=100',undefined,otherContext);assert(!otherAudit.body.items.some(r=>r.entity_id===company.id));const aEvent=audit.body.items.find(r=>r.entity_id===company.id);assert(aEvent);assert.equal((await api(admin,'/audit/'+aEvent.id,undefined,otherContext)).status,404);}
 stage='storage headers and browser errors';for(const ctx of [adminCtx,supportCtx])for(const p of ctx.pages()){const stores=await p.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)}));assert(stores.local.every(k=>k==='hiatlas-theme'));assert(stores.session.every(k=>k==='hiatlas.access-context.v1'));}assert(requests.length>0&&requests.every(r=>r.context));assert.equal(errors.length,0);assert.equal(unsafe.length,0);
 console.log('PASS Phase7: Admin hierarchy/create/edit/inactivate/cycle/PROJECT rejection; contracted and active modules/conflict/audit; Support read-only and manual403; A/A2/B nodes/parents/modules/audit isolation; themes/desktop/mobile/keyboard/context/storage; real PostgreSQL/FastAPI/React/Chrome; no external SMTP.');
}catch{const failed=browser.contexts().at(-1)?.pages().at(-1);if(failed)await failed.screenshot({path:path.join(process.env.HIATLAS_E2E_STATE,'phase07-failure.png'),fullPage:true}).catch(()=>{});console.error('FAIL Phase7 E2E at '+stage+' (sensitive diagnostics suppressed)');process.exitCode=1;}finally{await browser.close();}
