import {StrictMode} from 'react';
import {render,screen,fireEvent,cleanup,waitFor,within} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import App from '../App';
import {MaintenanceAdapters} from './registry';
import FixtureRenameForm from './FixtureRenameForm';
const action={action_code:'FIXTURE_NODE_RENAME',label:'Renomear nó controlado',entity_type:'organization_node',can_correct:true,can_reprocess:true};
const adapter={actionCode:'FIXTURE_NODE_RENAME',entityType:'organization_node' as const,Form:FixtureRenameForm};
const snapshot={kind:'DEPARTMENT',name:'Antes real',code:'NODE',parent_id:null,active:true,version:1};
const grant={id:'grant-a',context_id:'maintenance-a',parent_context_id:'parent-a',tenant_id:'tenant-a',tenant_name:'Empresa A',contract_id:'contract-a',contract_code:'CTR-A',environment:'TEST',operator:{user_id:'admin',display_name:'Admin',platform_role:'PLATFORM_ADMIN'},grant_type:'MAINTENANCE',status:'ACTIVE',version:1,reason:'Concessão controlada',reference:'SUP-1',started_at:'2026-10-03T12:00:00Z',expires_at:'2099-01-01T00:00:00Z',ended_at:null,revoked_at:null,scopes:[{action_code:'FIXTURE_NODE_RENAME',entity_type:'organization_node',entity_id:'entity-a'}]};
const run={id:'11111111-1111-4111-8111-111111111111',action_code:'FIXTURE_NODE_RENAME',status:'FAILED',result_code:'HANDLER_FAILED',message_code:'HANDLER_FAILED',request_id:'33333333-3333-4333-8333-333333333333',created_at:'2026-10-03T12:00:00Z',started_at:null,finished_at:null,version:1,can_reprocess:true,entity_id:'entity-a',source_run_id:null};
let active=false,applyStatus=200,reprocessStatus=200,granted=grant,previewCount=0;
const calls:{path:string;body:Record<string,unknown>;init:RequestInit}[]=[];
function response(data:unknown,status=200){return new Response(status===204?null:JSON.stringify(data),{status});}
beforeEach(()=>{active=false;applyStatus=200;reprocessStatus=200;granted=grant;previewCount=0;calls.length=0;sessionStorage.clear();localStorage.clear();sessionStorage.setItem('hiatlas.access-context.v1','parent-a');vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit={})=>{const p=url.replace('/api',''),body=JSON.parse(String(init.body??'{}'));calls.push({path:p,body,init});if(p==='/auth/me')return response({user_id:'admin',display_name:'Admin',platform_role:'PLATFORM_ADMIN'});if(p==='/auth/csrf')return response({token:'csrf'});if(p==='/auth/reauthenticate')return response(null,204);if(p==='/context')return response({id:'parent-a',tenant_name:'Empresa A',contract_id:'contract-a',contract_code:'CTR-A',environment:'TEST',expires_at:'2099-01-01T00:00:00Z',capabilities:['maintenance.authorize','memberships.read'],privileged_context_id:active?'maintenance-a':null});if(p==='/maintenance')return response({items:[action],mode:active?'MAINTENANCE':'NORMAL'});if(p.startsWith('/memberships?'))return response({items:[],total:0});if(p==='/grants'&&init.method==='POST'){active=true;return response(granted,201);}if(p==='/grants/context')return response(granted);if(p.startsWith('/maintenance/entities/'))return response(snapshot);if(p==='/maintenance/preview'){previewCount++;return response({action_code:action.action_code,entity_id:'entity-a',expected_version:1,before:snapshot,after:{...snapshot,name:body.proposed_input&&typeof body.proposed_input==='object'?(body.proposed_input as {name:string}).name:'Depois real',version:2},effects:['Nome atualizado'],preview_receipt:'opaque-secret-receipt'});}if(p==='/maintenance/corrections')return response({audit_event_id:'audit-a',action_code:action.action_code,entity_id:'entity-a',version:2},applyStatus);if(p.startsWith('/processings?'))return response({items:[run,{...run,id:'unknown-run',status:'UNKNOWN',can_reprocess:false,raw_log:'sentinel-secret'}],total:2,limit:20,offset:0});if(p==='/processings/11111111-1111-4111-8111-111111111111/reprocess')return response({...run,id:'22222222-2222-4222-8222-222222222222',status:'SUCCEEDED',result_code:'COMPLETED',message_code:'COMPLETED',source_run_id:run.id,can_reprocess:false},reprocessStatus);return response({},404);}));});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
function mount(){render(<StrictMode><MaintenanceAdapters.Provider value={[adapter]}><App/></MaintenanceAdapters.Provider></StrictMode>);}
async function requestGrant(){mount();fireEvent.click(await screen.findByRole('button',{name:'Manutenção'}));fireEvent.click(await screen.findByRole('button',{name:'Solicitar acesso de manutenção'}));fireEvent.change(screen.getByLabelText('Entidade autorizada'),{target:{value:'entity-a'}});fireEvent.change(screen.getByLabelText('Motivo do acesso de manutenção'),{target:{value:'Concessão controlada'}});fireEvent.change(screen.getByLabelText('Referência / chamado obrigatório'),{target:{value:'SUP-1'}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));fireEvent.click(await screen.findByRole('button',{name:'Confirmar acesso de manutenção'}));}
async function start(){await requestGrant();await screen.findByRole('region',{name:'Acesso temporário privilegiado'});}
async function preview(){await start();fireEvent.change(await screen.findByLabelText('Novo nome'),{target:{value:'Depois revisado'}});fireEvent.change(screen.getByLabelText('Motivo da correção'),{target:{value:'Corrigir nome controlado'}});fireEvent.change(screen.getByLabelText('Referência da correção'),{target:{value:'SUP-2'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Consultar prévia'})).not.toBeDisabled());fireEvent.click(screen.getByRole('button',{name:'Consultar prévia'}));await screen.findByRole('heading',{name:'Depois'});}
async function confirm(){fireEvent.click(screen.getByRole('button',{name:'Revisar confirmação'}));fireEvent.click(await screen.findByRole('button',{name:'Confirmar correção'}));}
it('maintenance grant requires reference reauth and explicit scope; banner includes context',async()=>{await start();const create=calls.find(c=>c.path==='/grants'&&c.init.method==='POST')!;expect(create.body).toEqual({grant_type:'MAINTENANCE',reason:'Concessão controlada',reference:'SUP-1',scopes:grant.scopes});expect(calls.find(c=>c.path==='/auth/reauthenticate')!.body).toEqual({password:'password'});expect(screen.getByRole('region',{name:'Acesso temporário privilegiado'})).toHaveTextContent('Referência: SUP-1');expect(screen.getByRole('region',{name:'Acesso temporário privilegiado'})).toHaveTextContent('FIXTURE_NODE_RENAME');expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBe('maintenance-a');expect(Object.values(sessionStorage)).not.toContain('Concessão controlada');});
it('specific typed adapter previews server before/after then contextual confirmation; success only from apply',async()=>{await preview();expect(screen.getByText('Antes real')).toBeVisible();expect(screen.getByText('Depois revisado')).toBeVisible();expect(calls.some(c=>c.path==='/maintenance/corrections')).toBe(false);expect(screen.queryByText('opaque-secret-receipt')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar confirmação'}));const dialog=screen.getByRole('dialog');expect(dialog).toHaveTextContent('Contrato: CTR-A');expect(dialog).toHaveTextContent('Corrigir nome controlado');fireEvent.click(within(dialog).getByRole('button',{name:'Confirmar correção'}));expect(await screen.findByText('Correção concluída e auditada.')).toBeVisible();expect(calls.find(c=>c.path==='/maintenance/corrections')!.body).toEqual({action_code:'FIXTURE_NODE_RENAME',entity_id:'entity-a',expected_version:1,proposed_input:{name:'Depois revisado'},reason:'Corrigir nome controlado',reference:'SUP-2',preview_receipt:'opaque-secret-receipt'});});
it('409 clears old preview and requires explicit refresh and fresh review without resubmission',async()=>{applyStatus=409;await preview();await confirm();expect(await screen.findByText('Os dados foram alterados desde a sua revisão.')).toBeVisible();expect(await screen.findByRole('button',{name:'Atualizar e revisar novamente'})).toBeVisible();expect(screen.queryByRole('heading',{name:'Depois'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Confirmar correção'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Atualizar e revisar novamente'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Consultar prévia'})).not.toBeDisabled());expect(calls.filter(c=>c.path==='/maintenance/corrections')).toHaveLength(1);expect(previewCount).toBe(1);});
it('failed apply never presents success or permits old preview reuse',async()=>{applyStatus=503;await preview();await confirm();expect(await screen.findByRole('alert')).toHaveTextContent('Serviço temporariamente indisponível');expect(screen.queryByText('Correção concluída e auditada.')).not.toBeInTheDocument();expect(screen.queryByRole('heading',{name:'Depois'})).not.toBeInTheDocument();});
it('minimal diagnostics omit raw logs and UNKNOWN offers no reprocessing',async()=>{await start();await screen.findByRole('button',{name:'Reprocessar'});expect(screen.queryByText('sentinel-secret')).not.toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Reprocessar'})).toHaveLength(1);expect(screen.queryByText('raw_log')).not.toBeInTheDocument();});
it('reprocessing reviews reason and preserves hidden idempotency key across explicit retry',async()=>{reprocessStatus=503;await start();fireEvent.click(await screen.findByRole('button',{name:'Reprocessar'}));fireEvent.change(screen.getByLabelText('Motivo do reprocessamento'),{target:{value:'Repetir após correção'}});fireEvent.change(screen.getByLabelText('Referência do reprocessamento'),{target:{value:'SUP-3'}});fireEvent.click(screen.getByRole('button',{name:'Revisar reprocessamento'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByRole('alert');reprocessStatus=200;fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByText('Reprocessamento concluído e auditado.');const requests=calls.filter(c=>c.path==='/processings/11111111-1111-4111-8111-111111111111/reprocess');expect(requests).toHaveLength(2);expect(requests[0].body.idempotency_key).toBe(requests[1].body.idempotency_key);expect(requests[0].body).toEqual({reason:'Repetir após correção',reference:'SUP-3',expected_version:1,idempotency_key:expect.any(String)});expect(screen.queryByText(String(requests[0].body.idempotency_key))).not.toBeInTheDocument();});

it('a creation response with a different authorized scope fails closed',async()=>{granted={...grant,scopes:[{...grant.scopes[0],entity_id:'unexpected-entity'}]};await requestGrant();await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(screen.queryByLabelText('Novo nome')).not.toBeInTheDocument();expect(screen.queryByRole('region',{name:'Acesso temporário privilegiado'})).not.toBeInTheDocument();});

it('maintenance review moves keyboard focus to contextual confirmation',async()=>{mount();fireEvent.click(await screen.findByRole('button',{name:'Manutenção'}));const opener=await screen.findByRole('button',{name:'Solicitar acesso de manutenção'});opener.focus();fireEvent.click(opener);const dialog=screen.getByRole('dialog');expect(screen.getByLabelText('Entidade autorizada')).toHaveFocus();fireEvent.change(screen.getByLabelText('Entidade autorizada'),{target:{value:'entity-a'}});fireEvent.change(screen.getByLabelText('Motivo do acesso de manutenção'),{target:{value:'Concessão controlada'}});fireEvent.change(screen.getByLabelText('Referência / chamado obrigatório'),{target:{value:'SUP-1'}});fireEvent.change(screen.getByLabelText('Confirme sua senha'),{target:{value:'password'}});fireEvent.click(screen.getByRole('button',{name:'Reautenticar e revisar'}));const confirmButton=await screen.findByRole('button',{name:'Confirmar acesso de manutenção'});expect(confirmButton).toHaveFocus();const cancel=within(dialog).getByRole('button',{name:'Cancelar'});cancel.focus();fireEvent.keyDown(cancel,{key:'Tab'});expect(confirmButton).toHaveFocus();fireEvent.keyDown(confirmButton,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Solicitar acesso de manutenção'})).toHaveFocus();});
it('revocation cancels delayed preview and discards late response and receipt',async()=>{await start();fireEvent.change(await screen.findByLabelText('Novo nome'),{target:{value:'Depois cancelado'}});fireEvent.change(screen.getByLabelText('Motivo da correção'),{target:{value:'Corrigir nome'}});await waitFor(()=>expect(screen.getByRole('button',{name:'Consultar prévia'})).not.toBeDisabled());const original=fetch;let finish:((value:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/maintenance/preview'?new Promise<Response>(resolve=>{finish=resolve;}):original(url,init)));fireEvent.click(screen.getByRole('button',{name:'Consultar prévia'}));await waitFor(()=>expect(finish).toBeDefined());granted={...grant,status:'REVOKED'};fireEvent(window,new Event('focus'));await screen.findByRole('heading',{name:'Selecionar ambiente'});finish!(response({action_code:action.action_code,entity_id:'entity-a',expected_version:1,before:snapshot,after:{...snapshot,name:'Late mutation'},effects:[],preview_receipt:'late-secret'}));await waitFor(()=>expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull());expect(screen.queryByRole('heading',{name:'Depois'})).not.toBeInTheDocument();expect(screen.queryByText('Late mutation')).not.toBeInTheDocument();expect(screen.queryByText('late-secret')).not.toBeInTheDocument();expect(calls.some(c=>c.path==='/maintenance/corrections')).toBe(false);});
it('maintenance expiry removes workspace and clears opaque context',async()=>{granted={...grant,expires_at:new Date(Date.now()+800).toISOString()};await start();await screen.findByRole('heading',{name:'Selecionar ambiente'},{timeout:2000});expect(screen.queryByLabelText('Novo nome')).not.toBeInTheDocument();expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull();expect(calls.some(c=>c.path==='/maintenance/corrections')).toBe(false);});
it('403 correction denial clears preview and revalidates revoked access',async()=>{applyStatus=403;await preview();granted={...grant,status:'REVOKED'};await confirm();await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(screen.queryByRole('heading',{name:'Depois'})).not.toBeInTheDocument();expect(screen.queryByText('Correção concluída e auditada.')).not.toBeInTheDocument();});
it('normal controlled diagnostics require grant before exposing any execution button',async()=>{mount();fireEvent.click(await screen.findByRole('button',{name:'Manutenção'}));await screen.findByText('Falhou');expect(screen.queryByRole('button',{name:'Reprocessar'})).not.toBeInTheDocument();expect(screen.getAllByText('33333333-3333-4333-8333-333333333333').length).toBeGreaterThan(0);});

it('final correction dialog itself shows before after and known effects',async()=>{await preview();fireEvent.click(screen.getByRole('button',{name:'Revisar confirmação'}));const dialog=within(screen.getByRole('dialog'));expect(dialog.getByRole('heading',{name:'Antes'})).toBeVisible();expect(dialog.getByText('Antes real')).toBeVisible();expect(dialog.getByRole('heading',{name:'Depois'})).toBeVisible();expect(dialog.getByText('Depois revisado')).toBeVisible();expect(dialog.getByText('Nome atualizado')).toBeVisible();});

it('reprocess contextual review focuses confirmation for keyboard use',async()=>{await start();fireEvent.click(await screen.findByRole('button',{name:'Reprocessar'}));fireEvent.change(screen.getByLabelText('Motivo do reprocessamento'),{target:{value:'Repetir após correção'}});fireEvent.click(screen.getByRole('button',{name:'Revisar reprocessamento'}));expect(await screen.findByRole('button',{name:'Confirmar reprocessamento'})).toHaveFocus();});

async function reviewReprocessing(){await start();fireEvent.click(await screen.findByRole('button',{name:'Reprocessar'}));fireEvent.change(screen.getByLabelText('Motivo do reprocessamento'),{target:{value:'Repetir após correção'}});fireEvent.change(screen.getByLabelText('Referência do reprocessamento'),{target:{value:'SUP-RECOVERY'}});fireEvent.click(screen.getByRole('button',{name:'Revisar reprocessamento'}));}
it('503 intent survives focus restoration unmount and explicit replay uses same key',async()=>{reprocessStatus=503;await reviewReprocessing();fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByRole('alert');const first=calls.find(c=>c.path.endsWith('/reprocess'))!;const original=fetch;let verify:((value:Response)=>void)|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url==='/api/grants/context'?new Promise<Response>(resolve=>{verify=resolve;}):original(url,init)));fireEvent(window,new Event('focus'));await screen.findByText('Validando acesso temporário…');expect(screen.queryByRole('button',{name:'Confirmar reprocessamento'})).not.toBeInTheDocument();await waitFor(()=>expect(verify).toBeDefined());reprocessStatus=200;verify!(response(granted));fireEvent.click(await screen.findByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByText('Reprocessamento concluído e auditado.');const retries=calls.filter(c=>c.path.endsWith('/reprocess'));expect(retries).toHaveLength(2);expect(retries[1].body).toEqual(first.body);expect(Object.values(sessionStorage).join(' ')).not.toContain(String(first.body.idempotency_key));});
it('pending committed response interrupted by restoration only replays the original intent',async()=>{await reviewReprocessing();const original=fetch;let finish:((value:Response)=>void)|undefined,verify:((value:Response)=>void)|undefined;const requests:Record<string,unknown>[]=[];let hold=true;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url.endsWith('/reprocess')){requests.push(JSON.parse(String(init?.body)));if(hold)return new Promise<Response>(resolve=>{finish=resolve;});}if(url==='/api/grants/context')return new Promise<Response>(resolve=>{verify=resolve;});return original(url,init);}));fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await waitFor(()=>expect(finish).toBeDefined());fireEvent(window,new Event('focus'));await screen.findByText('Validando acesso temporário…');expect(screen.queryByRole('button',{name:'Reprocessar'})).not.toBeInTheDocument();await waitFor(()=>expect(verify).toBeDefined());finish!(response({...run,id:'22222222-2222-4222-8222-222222222222',source_run_id:run.id,status:'SUCCEEDED',result_code:'COMPLETED',message_code:'COMPLETED',can_reprocess:false}));hold=false;verify!(response(granted));fireEvent.click(await screen.findByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByText('Reprocessamento concluído e auditado.');expect(requests).toHaveLength(2);expect(requests[1]).toEqual(requests[0]);});
it.each([{id:'not-a-uuid'},{action_code:'OTHER_ACTION'},{entity_id:'other-entity'},{source_run_id:'44444444-4444-4444-8444-444444444444'},{source_run_id:null},{version:0},{request_id:null},{status:'INVALID'},{result_code:'INVALID'},{message_code:'INVALID'}])('mismatched or incomplete reprocess projection %j never announces success and preserves same-key replay',async broken=>{await reviewReprocessing();const original=fetch;let malformed=true;const submitted:Record<string,unknown>[]=[];vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>{if(url.endsWith('/reprocess')){submitted.push(JSON.parse(String(init?.body)));if(malformed)return Promise.resolve(response({...run,id:'22222222-2222-4222-8222-222222222222',source_run_id:run.id,status:'SUCCEEDED',result_code:'COMPLETED',message_code:'COMPLETED',can_reprocess:false,...broken}));}return original(url,init);}));fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByRole('alert');expect(screen.queryByText('Reprocessamento concluído e auditado.')).not.toBeInTheDocument();malformed=false;fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByText('Reprocessamento concluído e auditado.');expect(submitted).toHaveLength(2);expect(submitted[1]).toEqual(submitted[0]);});

it('submitted ambiguous intent cannot be replaced by closing and starting a fresh reprocess',async()=>{reprocessStatus=503;await reviewReprocessing();fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByRole('alert');const originalCommand=calls.find(c=>c.path.endsWith('/reprocess'))!.body;fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Cancelar'}));expect(screen.queryByRole('button',{name:'Reprocessar'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Revisar tentativa pendente'}));reprocessStatus=200;fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await screen.findByText('Reprocessamento concluído e auditado.');expect(calls.filter(c=>c.path.endsWith('/reprocess')).at(-1)!.body).toEqual(originalCommand);});
it('revocation aborts submitted intent and discards late committed projection',async()=>{await reviewReprocessing();const original=fetch;let finish:((value:Response)=>void)|undefined,signal:AbortSignal|undefined;vi.stubGlobal('fetch',vi.fn((url:string,init?:RequestInit)=>url.endsWith('/reprocess')?new Promise<Response>(resolve=>{finish=resolve;signal=init?.signal??undefined;}):original(url,init)));fireEvent.click(screen.getByRole('button',{name:'Confirmar reprocessamento'}));await waitFor(()=>expect(finish).toBeDefined());granted={...grant,status:'REVOKED'};fireEvent(window,new Event('focus'));await screen.findByRole('heading',{name:'Selecionar ambiente'});expect(signal?.aborted).toBe(true);finish!(response({...run,id:'22222222-2222-4222-8222-222222222222',source_run_id:run.id,status:'SUCCEEDED',result_code:'COMPLETED',message_code:'COMPLETED',can_reprocess:false}));expect(screen.queryByText('Reprocessamento concluído e auditado.')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Revisar tentativa pendente'})).not.toBeInTheDocument();expect(sessionStorage.getItem('hiatlas.privileged-context.v1')).toBeNull();});
