// Controlled test adapter. Never imported by the normal application entry.
import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../auth/state';
import {usePrivileged} from '../privileged/state';
import {ApiError,isAbort} from '../api/errors';
import ErrorNotice from '../api/ErrorNotice';
import AccessDialog from '../platform/access/AccessDialog';
import type {MaintenanceAction} from './registry';
type Snapshot={kind:string;name:string;code:string;parent_id:string|null;active:boolean;version:number};
type Command={action_code:string;entity_id:string;expected_version:number;proposed_input:{name:string};reason:string;reference:string|null};
type Preview={action_code:string;entity_id:string;expected_version:number;before:Snapshot;after:Snapshot;effects:string[];preview_receipt:string};
function snapshot(value:Snapshot){if(!value||typeof value.name!=='string'||typeof value.code!=='string'||typeof value.active!=='boolean'||!Number.isInteger(value.version)||value.version<1)throw new ApiError(503);return value;}
function SnapshotView({title,value}:{title:string;value:Snapshot}){return <article><h3>{title}</h3><dl><dt>Nome</dt><dd>{value.name}</dd><dt>Código</dt><dd>{value.code}</dd><dt>Versão</dt><dd>{value.version}</dd><dt>Situação</dt><dd>{value.active?'Ativo':'Inativo'}</dd></dl></article>;}
export default function FixtureRenameForm({action,entityId}:{action:MaintenanceAction;entityId:string}){
 const {api}=useAuth(),privileged=usePrivileged()!,contextId=privileged.grant?.context_id,retry=privileged.retry;
 const [entity,setEntity]=useState<Snapshot|null>(null),[name,setName]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[preview,setPreview]=useState<{value:Preview;command:Command}|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[conflict,setConflict]=useState(false),[success,setSuccess]=useState(false),[revision,setRevision]=useState(0),[denied,setDenied]=useState(false);
 const controller=useRef<AbortController|null>(null),generation=useRef(0),locked=useRef(false);
 useEffect(()=>{const abort=new AbortController(),epoch=++generation.current;controller.current=abort;api.request<Snapshot>(`/maintenance/entities/${encodeURIComponent(action.action_code)}/${encodeURIComponent(entityId)}`,{contextId,signal:abort.signal}).then(value=>{snapshot(value);if(!abort.signal.aborted&&epoch===generation.current)setEntity(value);}).catch(e=>{if(!abort.signal.aborted&&epoch===generation.current&&!isAbort(e)){setError(e);if(e instanceof ApiError&&[401,403,404].includes(e.status)){setDenied(true);retry();}}});return()=>abort.abort();},[api,contextId,entityId,action.action_code,revision,retry]);
 function clearReview(){setPreview(null);setConfirm(false);setSuccess(false);setError(null);}
 async function requestPreview(){if(locked.current||!entity||!contextId||denied||conflict)return;locked.current=true;setBusy(true);clearReview();const abort=controller.current!,epoch=generation.current;const command:Command={action_code:action.action_code,entity_id:entityId,expected_version:entity.version,proposed_input:{name:name.trim()},reason:reason.trim(),reference:reference.trim()||null};try{const value=await api.request<Preview>('/maintenance/preview',{method:'POST',contextId,signal:abort.signal,body:command});snapshot(value.before);snapshot(value.after);if(value.action_code!==action.action_code||value.entity_id!==entityId||value.expected_version!==entity.version||value.before.version!==entity.version||!value.preview_receipt||!Array.isArray(value.effects)||value.effects.some(v=>typeof v!=='string'))throw new ApiError(503);if(!abort.signal.aborted&&epoch===generation.current)setPreview({value,command});}catch(e){handleError(e,abort,epoch);}finally{locked.current=false;if(!abort.signal.aborted&&epoch===generation.current)setBusy(false);}}
 function handleError(e:unknown,abort:AbortController,epoch:number){if(abort.signal.aborted||epoch!==generation.current||isAbort(e))return;setPreview(null);setConfirm(false);setError(e);if(e instanceof ApiError&&e.status===409){setConflict(true);setEntity(null);}if(e instanceof ApiError&&[401,403,404].includes(e.status)){setDenied(true);setEntity(null);retry();}}
 async function apply(){if(!preview||locked.current||!contextId||denied)return;locked.current=true;setBusy(true);setError(null);const abort=controller.current!,epoch=generation.current;try{const value=await api.request<{audit_event_id:string;action_code:string;entity_id:string;version:number}>('/maintenance/corrections',{method:'POST',contextId,signal:abort.signal,body:{...preview.command,preview_receipt:preview.value.preview_receipt}});if(!value.audit_event_id||value.action_code!==action.action_code||value.entity_id!==entityId||!Number.isInteger(value.version))throw new ApiError(503);if(!abort.signal.aborted&&epoch===generation.current){setSuccess(true);setPreview(null);setConfirm(false);setEntity(null);setRevision(v=>v+1);}}catch(e){handleError(e,abort,epoch);}finally{locked.current=false;if(!abort.signal.aborted&&epoch===generation.current)setBusy(false);}}
 return <section aria-label="Correção controlada"><h3>{action.label}</h3><p>Entidade autorizada: {entityId}</p><ErrorNotice error={conflict?null:error}/>{conflict&&<p role="alert">Os dados foram alterados desde a sua revisão.</p>}{success&&<p role="status">Correção concluída e auditada.</p>}{conflict?<button disabled={busy} onClick={()=>{clearReview();setConflict(false);setEntity(null);setRevision(v=>v+1);}}>Atualizar e revisar novamente</button>:denied?<p>A operação está indisponível. Valide o acesso temporário para continuar.</p>:<>{!entity&&<p role="status">Consultando entidade autorizada…</p>}<form onSubmit={e=>{e.preventDefault();void requestPreview();}}><label htmlFor="rename-name">Novo nome</label><input id="rename-name" required maxLength={200} value={name} disabled={busy} onChange={e=>{setName(e.target.value);clearReview();}}/><label htmlFor="rename-reason">Motivo da correção</label><textarea id="rename-reason" required minLength={3} maxLength={1000} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);clearReview();}}/><label htmlFor="rename-reference">Referência da correção</label><input id="rename-reference" maxLength={100} value={reference} disabled={busy} onChange={e=>{setReference(e.target.value);clearReview();}}/><button disabled={busy||!entity||!name.trim()||reason.trim().length<3}>Consultar prévia</button></form>{preview&&<><div className="maintenance-snapshots"><SnapshotView title="Antes" value={preview.value.before}/><SnapshotView title="Depois" value={preview.value.after}/></div><ul>{preview.value.effects.map((effect,index)=><li key={index}>{effect}</li>)}</ul><button disabled={busy} onClick={()=>setConfirm(true)}>Revisar confirmação</button></>}</>}{confirm&&preview&&<AccessDialog title="Confirmar correção de manutenção" busy={busy} onClose={()=>setConfirm(false)}><p>Ação: {action.label}</p><p>Entidade: {entityId}</p><p>Versão revisada: {preview.command.expected_version}</p><p>Motivo: {preview.command.reason}</p><p>Referência: {preview.command.reference??'Não informada'}</p><div className="maintenance-snapshots"><SnapshotView title="Antes" value={preview.value.before}/><SnapshotView title="Depois" value={preview.value.after}/></div><ul>{preview.value.effects.map((effect,index)=><li key={index}>{effect}</li>)}</ul><p>Aplicar o nome revisado: {preview.command.proposed_input.name}?</p><button disabled={busy} onClick={()=>void apply()}>Confirmar correção</button></AccessDialog>}</section>;
}
